* Syllabus

** Where and when
Steward Observatory room 204
Tuesday and Thursday 12:30-1:45pm

** Instructors
*** Professor: Mathieu Renzo
- Office: N506
- Email: mrenzo@arizona.edu
- Office hours: by appointment

*** TA: Hailey Bowden
- Email: hbowden@arizona.edu
- Office hours: by appointment

** Description of the course
The main topic of the course is stellar structure, a field of
astronomy that brings many different branches of physics to understand
the fundamental objects of astronomical study: stars. Toward the end
of the semester, we may discuss several other related topics as well,
including planet formation and stellar explosions.

** TODO Course format and teaching methods
This class relies heavily on in-class problem solving activities, and
work in small groups. Some of these will be of computational nature.

This is also a class with "writing emphasis", which will be included
as part of the in class activities and homework.

** Expected learning outcomes

By the end of the course, students will:

 - Apply a theoretical framework to stellar structure and derive from first
   principles stellar properties that match observations.
 - Develop an understanding of fundamental theoretical astrophysics,
   that can be applied to a broad range of specific problems.
 - Use mathematical and computational skills to solve astrophysical problems.
 - Develop proficiency with communicating, translating, and
   interpreting fundamental astronomical concepts and research results
   in oral and/or written formats.
 - Gain knowledge of the physical scales, masses, sizes, lifetimes and
   other properties associated with a wide variety of astronomical
   objects and phenomena

These learning outcomes will be met through attendance of lectures,
homework and writing assignments, in-class activities, and in-class
exams.


** TODO Exams

** TODO Grading

** Recommended textbooks
Most stellar physics text books will contain most of the information
covered in this course, although order and presentation can vary
widely. I recommend the following:

 - [[https://www.astro.ru.nl/~onnop/][Onno Pols notes]]. These lecture notes are freely available,
   accessible, and thorough, making them an excellent starting point.
   I recommend downloading a copy for yourself early in the course.
 - [[https://link.springer.com/book/10.1007/978-3-642-30304-3][Kippenhahn, Weigert, & Weiss 2012]]. This is a classic textbook that
   you may continue to consult even as a seasoned researcher with
   emphasis on the physical processes in stars. Students enrolled
   in the class should come talk to me if you have issues getting this
   book.

** TODO Classwork and homework

** Accessibility and accommodations
At the University of Arizona, we strive to make learning
experiences as accessible as possible. If you anticipate or
experience barriers based on disability or pregnancy, please
contact the Disability Resource Center (520-621-3268,
https://drc.arizona.edu/) to establish reasonable accommodations.

** Academic Integrity
According to the Arizona Code of Academic Integrity, “Integrity is
expected of every student in all academic work. The guiding principle
of academic integrity is that a student’s submitted work must be the
student’s own.” Students are encouraged to share intellectual views
and discuss freely the principles and applications of course
materials. However, *graded work/exercises must be the product of
independent effort unless otherwise instructed*. Students are expected
to adhere to the UA Code of Academic Integrity as described in the UA
General Catalog. See:
https://deanofstudents.arizona.edu/student-rights-responsibilities/
academic-integrity

Misappropriation of exams before or after they are given will be
considered academics misconduct. Misconduct of any kind will be
prosecuted and may result in any or all of the following:
- Reduction of grade
- Failing grade
- Referral to the Dean of Students for consideration of additional penalty, i.e.
notation on a student’s transcript re. academic integrity violation, etc.
http://deanofstudents.arizona.edu/policies‐and‐codes/code‐academic‐integrity

** Attendance Policy
It is important to attend all classes, as what is discussed in class is pertinent to
adequate performance on assignments and exams. If you must be absent, it is your
responsibility to obtain and review the information you missed.

All holidays or special events observed by organized religions will be honored
for those students who show affiliation with that particular religion. Absences
pre‐approved by the UA Dean of Students (or Dean's designee) will be honored.

** Classroom Behavior
The Arizona Board of Regents’ Student Code of Conduct, ABOR Policy 5‐308,
prohibits threats of physical harm to any member of the University community,
including to one’s self. See:
http://policy.web.arizona.edu/threatening‐behavior‐students


** Subject to change statement
The information contained in this syllabus, other than the grade and absence
policies, may be subject to change with reasonable advance notice, as deemed
appropriate by the instructor.
