* Lectures topic-by-topic
This is a rough schedule of topics. However, we may not get to all
topics, depending on progress throughout the semester and student
interest. The order roughly follows the presentation in [[https://www.astro.ru.nl/~onnop/][Onno Pols
notes]].


** Intro & orders of magnitude

*** Introduction to the course

  - introduce yourself
  - Discuss [[./syllabus.org][syllabus]] and learning outcomes specifically


*** Relevant physical scales

  The star we can observe best is the closest one, the Sun (\odot), so a
  lot of quantities are scaled to those of the Sun in stellar physics
  and in astronomy more generally.

**** Solar radius
     R_{\odot} = 6.957\times 10^{10} cm \simeq 7\times10^{10} cm \simeq 10^{11} cm

**** Solar mass
     M_{\odot} = 1.98\times10^{33} g\simeq 2\times10^{33} g

**** Solar luminosity
     L_{\odot} = 3.82\times10^{33}^{}^{} erg s^{-1} \simeq 2\times M_{\odot} in =cgs units=!

     (This may be one of the reasons why we still use =cgs= in astronomy,
     the other one being that the constants in electromagnetism are a
     bit simpler).

**** Lifetime
     Lifetimes: ~3 Myr to \gg age of the Universe (\simeq 13.7 Gyr)

     How old is the Sun? How long will it live?


** Color-magnitude and Hertzsprung-Russell diagram

  How can we study things that evolve too slow for us to see?

*** Hertzsprung-Russel diagram visualization

   HRD video: https://www.youtube.com/watch?v=PsS80huL47c

*** Homework idea

  - download and plot a bunch of Gaia data. Make the visualization as
    clear as possible


** Hydrostatic equilibrium

** Virial theorem, pressure, estimates
 - discuss stability


** Equation of state 1
- Polytropic Equation of state
- Ideal gas

** Equation of state 2
- Degenerate and non-relativistic gas
- Degenerate and relativistic gas
- Radiation-dominated

*** Homework idea
 - derive the Chandrasekhar mass?


** Radiative energy transport & conduction
- opacity


** Convection

** Nuclear energy generation

*** Homework idea

  - run MESA web and compare lifetimes without nuclear energy
    generation and with it


** Evolution: low mass stars

** Evolution: high mass stars

** Eclipsing binaries

** Supernovae
