* Lectures topic-by-topic

** Lecture 1: Intro & orders of magnitude

*** Introduction to the course

  - introduce yourself
  - Discuss [[./syllabus.org][syllabus]] and learning outcomes specifically


*** Relevant physical scales

  The star we can observe best is the closest one, the Sun (\odot), so a
  lot of quantities are scaled to those of the Sun in stellar physics
  and in astronomy more generally.

**** Solar radius
     R_{\odot} = 6.957\times 10^{10} cm \simeq 10^{11} cm

**** Solar mass
     M_{\odot} = 2\times10^{33} g

**** Solar luminosity
     L_{\odot} = 3.82\times10^{33}^{}^{} erg s^{-1} \simeq 2\times M_{\odot} in =cgs units=!

     This may be one of the reasons why we still use =cgs= in astronomy,
     the other one being that the constants in electromagnetism are a
     bit simpler.

**** Lifetime
     Lifetimes: ~3 Myr to \gg age of the Universe (\simeq 13.7 Gyr)

     How old is the Sun? How long will it live?

** Lecture 2: Color-magnitude and Hertzsprung-Russell diagram

  How can we study things that evolve too slow for us to see?


*** Hertzsprung-Russel diagram visualization

   HRD video: https://www.youtube.com/watch?v=PsS80huL47c

*** Homework idea

  - download and plot a bunch of Gaia data. Make the visualization as
    clear as possible

** Lecture 3: Hydrostatic equilibrium

** Lecture 4: Virial theorem, pressure, estimates

** Lecture 5: Nuclear energy generation

*** Homework idea

  - run MESA web and compare lifetimes without nuclear energy
    generation and with it
