#+title: 400A - opacity
#+author: Mathieu Renzo
#+email: mrenzo@arizona.edu

* Opacity
*Materials*: Chapter 5 of Onno Pols' lecture notes, Sec. 5.1.3 of
Kippenhahn's book.

We have seen in [[file:notes-lecture-ETransport.org::*Energy transport by conduction][the previous lecture]] that in the equation for the
energy transport by diffusion (either of photons or electrons, that is
either radiative or conductive energy transport) there is a parameter
\kappa that determines the "resistance" of the stellar gas to the passage
of energy by diffusion. This was the analogy that comes out from the
combination of the radiative opacity and conductive opacity

#+begin_latex
\begin{equation}\label{eq:kappas}
\frac{1}{\kappa} = \frac{1}{\kappa_\mathrm{rad}} + \frac{1}{\kappa_\mathrm{cond}} \ \ .
\end{equation}
#+end_latex

Since we also saw that dT/dr \propto \kappa F, it is clear that the opacity \kappa is
an extremely important parameter for the structure of the star.
Effectively, what that proportionality means is that given an opacity
profile \kappa\equiv\kappa(r(m)), the stellar structure will adjust in such a way
that the temperature gradient dT/dr is sufficient to carry out the
flux F that is necessary to maintain energy conservation
layer-by-layer (accounting for the energy losses at the surface and
throughout because of e.g., neutrinos)!

The purpose of this lecture is to focus on \kappa_{rad} and understand what
physically determines it, and understand how \kappa_{rad}\equiv\kappa_{rad}(T,
\rho, \{X_{i}\}) can be expressed as a function of the thermodynamics and
composition of the stellar gas.

* Rosseland mean opacity

But even before we discuss the microphysics, you know that the
"resistance" of a material to the passage of light is dependent on the
frequency of the radiation! Optical radiation clearly penetrates the
Earth atmosphere, while X-rays don't; the small fraction of UV
radiation that does penetrate the atmosphere and cause Sun burns does
not penetrate the windshield of a car, but the optical wavelengths do,
etc. So clearly in general \kappa_{rad} \equiv \kappa_{rad}(\nu) is a function of
the frequency of the light we are considering with \nu = c/\lambda. What
happened to that dependence in our stellar structure equations?

In the [[./notes-lecture-ETransport.org::*Energy transport by radiative diffusion][previous lecture]] we have written for the radiative energy flux

#+begin_latex
\begin{equation}
F_\mathrm{rad} = - \frac{1}{3}\frac{c}{\kappa_\mathrm{rad}\rho}\frac{du}{dr} \ \ .
\end{equation}
#+end_latex

In reality, we should have written an equation like this for the
specific flux (i.e., the radiative flux F_{\nu} carried by radiation with
frequency between \nu and \nu+d\nu) and integrate over the spectrum to get
F_{rad} =\int_{0}^{+\infty} F_{\nu} n(\nu) d\nu, with n(\nu) number density of
photons ad a function of frequency. For the specific flux, we also
should put in the equation the specific opacity \kappa_{\nu}_{} and consider only
the energy density of radiation u_{\nu} between \nu and \nu+d\nu:

#+begin_latex
\begin{equation}
F_{\nu} = - \frac{1}{3}\frac{c}{\kappa_{\nu}\rho}\frac{du_{\nu}}{dr} \ \ .
\end{equation}
#+end_latex

Recall that u_{\nu} = h\nu n(\nu) and n(\nu) is determined by the
condition of LTE (which is approximately correct in the stellar
interior), which means the photons are distributed according to a
black body distribution:

#+begin_latex
\begin{equation}
u_{\nu} = \frac{4\pi}{c}B(\nu, T) = \frac{8\pi h}{c^{3}}\frac{\nu^{3}}{e^{h\nu/k_{B}T} -1} \ \ .
\end{equation}
#+end_latex

Thus du_{\nu}/dr = 4\pi/c \times \partial B(\nu, T)/\partial T \times dT/
dr, and performing the integral over the
frequencies:

#+begin_latex
\begin{equation}
F_\mathrm{rad} = \int_{0}^{+\infty} F_{\nu}d\nu = - \frac{1}{3}\frac{c}{\rho}\int_{0}^{+\infty} \frac{1}{\kappa_{\nu}}\frac{du_{\nu}}{dr} =
-\frac{4\pi}{3c\rho}\int_{0}^{+\infty}\frac{1}{\kappa_{\nu}}\frac{\partial B(\nu, T)}{\partial T} d\nu \frac{dT}{dr} \ \ .
\end{equation}
#+end_latex

Comparing this with Eq. 8 from the previous lecture we obtain that the
\kappa_{rad} appearing there must be:

#+begin_latex
\begin{equation}
\frac{1}{\kappa_\mathrm{rad}} = \frac{\pi}{acT^{3}}\int_{0}^{+\infty} d\nu \frac{1}{\kappa_{\nu}}\frac{\partial B(\nu, T)}{\partial T} \ \ ,
\end{equation}
#+end_latex
which we can rewrite as

#+begin_latex
\begin{equation}
\frac{1}{\kappa_\mathrm{rad}} = \frac{\int_{0}^{+\infty} d\nu \frac{1}{\kappa_{\nu}}\frac{\partial B(\nu, T)}{\partial T}}{\int_{0}^{+\infty} d\nu \frac{\partial B(\nu, T)}{\partial T}} \ \ ,
\end{equation}
#+end_latex
which is the /harmonic mean of specific opacities/ \kappa_{\nu} /weighted
with the temperature derivative of the Black Body distribution/.
This is usually referred to as the Rosseland mean opacity.

** Physical interpretation
This may seem like a bunch of math that did not advance us much: we
still have \kappa_{\nu} (which in practice comes from atomic physics
experimental and theoretical work), and the Rosseland mean opacity
seems to not have a straightforward physical interpretation.

However, consider that to a good approximation we can consider the
stellar interior to be in LTE with a single temperature and a photon
gas described by a black body. Therefore at a location in the star of
given \rho and dT/dr, the frequency \nu at which most of the photon energy
is found by solving \partial u_{\nu} / \partial T = 0, which yields a maximum at
h\nu = 4k_{B}T. This means that the Rosseland mean tends to "upweight" where
most of the radiation energy is, and "down weight" the very low and
very high frequencies.

In other words, 1/\kappa_{rad} is smallest where most of the radiation energy
can get through (which makes sense since we are developing an
understanding for how energy is transported, and not for how energy is
trapped!).

An unfortunate consequence of the harmonic nature of the Rosseland
mean opacity is that it is not trivial to combine opacity of different
gasses, the specific \kappa_{\nu} have to be summed *before* taking the average.


* Sources of radiative opacity

Now, let's consider the radiation-matter interactions that can be
source of opacity (i.e., determine the \kappa_{\nu} that we put in the
Rosseland mean opacity to obtain \kappa_{rad}).

** Bound-bound

** Bound-free

** Free-free

** Scattering


TODO: show MESA plot of \kappa(T,\rho)
