#+title: 400A - EOS (degenerate)
#+author: Mathieu Renzo
#+email: mrenzo@arizona.edu

* Equation of state 2/2
*Materials*: Chapter 3 of Onno Pols' lecture notes, Chapter 15 and 16 of
Kippenhahn's book.

In the [[./notes-lecture-EOS1.org][previous lecture on EOS]], we have discussed polytropic EOS and
classical, non-relativistic, ideal gas. The latter is an accurate
description of the stellar gas in most, but importantly not /all/ the
astrophysical cases.

We will consider now cases that don't verify the hypothesis we took
previously and discuss briefly some stars for which we need to go
beyond those.

** Quantum-mechanical effects

A star is "big", why do we need to care about quantum mechanics (QM)?
Besides its central role in allowing for nuclear burning, [[file:materials/nuclear_reaction_rates.pdf][which we
will see later]], QM effects can matter also at extremely low
temperatures and/or high densities, which can be encountered in
stellar physics.

From the wave-nature of the solutions of Schroedinger's equation, we
know that there is a limit on the precision to which position and
velocity of a particle can be known ("Heisenberg's uncertainty
principle"): \Delta x \Delta p \ge h with h Planck's constant. This naturally
translates in three spatial dimension to

#+begin_latex
\begin{equation}
\Delta x \Delta y \Delta z \Delta p_{x} \Delta p_{y} \Delta p_{z} \ge h^{3} \ \,
\end{equation}
#+end_latex

where h^{3} is the volume of a quantized cell in phase-space! Thus the
available number of quantized states with momentum between p+dp within
a volume dV is

#+begin_latex
\begin{equation}
g(p)dpdV = g_{s} \frac{4\pi p^{2} dp dV}{h^{3}} \ \mathrm{with}\ p=\sqrt{p_{x}^{2} +p_{y}^{2} +p_{z}^{2}} .
\end{equation}
#+end_latex
In the equation above, the factor g_{s} allows to account for "internal
degrees of freedom" of particles, e.g., their spin, polarization, or
isospin. The key point here is f(p)\propto p^{2} to satisfy QM.


Let's start by considering a non-extreme situation. Then the particles
are distributed according to a Maxwellian distribution n(p), but
whenever n(p)> g(p), we know this is going to violate QM!

From the [[file:notes-lecture-EOS1.org::*Ideal gas][previous lecture on EOS]] we know that the Maxwell-Boltzmann
distribution is

#+begin_latex
\begin{equation}
n(p)\propto \frac{n}{(mT)^{3/2}} \exp\left(\frac{-p^{2}}{2mk_{B} T}\right)p^{2 }\ \ ,
\end{equation}
#+end_latex

where n is the number density, T the temperature, and m the mass of
the particles. Therefore:

#+begin_latex
\begin{equation}
\frac{n(p)}{g(p)}\propto n (mT)^{-3/2}\exp(-p^{2}/2mk_{B}T) \ \ .
\end{equation}
#+end_latex

We can see that:

- at fixed temperature T, for very high number densities n, this ratio
  is going to be larger than one in violation of QM
- at fixed number density n, for very low temperatures, this ratio
  will be larger than 1 in violation of QM (because every term in the
  Taylor expansion of the exponential is proportional to a negative
  power of T).

Thus, we can expect that for very "cold" stars (we will define what is
the relevant scale here) or vey dense stars the ideal gas EOS will not
be appropriate.

To account for QM effects, we need to consider the nature of the
particles making up the star, which can be either

- *Fermions* with semi-integer spin, such as electrons, protons,
  neutrons (and protons and neutrons can be seen as two isospin state
  of a generic nucleon, this is useful for example to discuss the
  interior composition of neutron stars). In this case, the
  distribution function that determines the occupation of quantum
  states of energy between \varepsilon\equiv\varepsilon(p) and \varepsilon+d\varepsilon is the Fermi-Dirac
  distribution:

  #+begin_latex
  \begin{equation}\label{eq:Fermi-Dirac}
   f_{FD}(\varepsilon) = \frac{1}{e^{(\varepsilon/k_{B}T - \eta)}+1} \le 1 \ \,
  \end{equation}
  #+end_latex

  where \eta=\mu/k_{b}T is the "degeneracy parameter" dependent on the
  /chemical potential \mu/ (*N.B.:* do not confuse this with the mean
  molecular weight which has the same symbol, the chemical potential
  has the dimension of an energy, while the mean molecular weight is a
  dimensionless number!) and the temperature. The fact that this is \le 1 is an
  expression of Pauli's exclusion principle, no two fermions can
  occupy the same quantum energy level.

- *Bosons* with integer spin, such as photons, or \alpha particles. In this
  case the relevant distribution is the Bose-Einstein's distribution:

  #+begin_latex
  \begin{equation}\label{eq:Bose-Einstein}
   f_{BE}(\varepsilon) = \frac{1}{e^{(\varepsilon/k_{B}T-\eta)}-1} \ \,
  \end{equation}
  #+end_latex

  which can be \ge 1, meaning more than one boson can occupy the same
  energy level (e.g., in the extreme case of a Bose-Einstein
  condensate all particles occupy the level with lowest \varepsilon).

  The total number of particles with momentum between p and p+dp is
  thus given by f(\varepsilon(p))g(p)dp for an appropriate choice of f depending
  on the particle considered (f=f_{FD} or f=f_{BE}). To determine the
  chemical potential \mu one can impose the normalization following
  from the total number density of particles:

  #+begin_latex
  \begin{equation}
  n = \int_{0}^{+\infty} f(\varepsilon(p))g(p)dp \ \ .
  \end{equation}
  #+end_latex

  Let's now consider a gas of electrons. These are the particles in
  the ionized gas of the star that will first start feeling QM
  effects, since m_{e} \ll m_{ion} (in fact m_{e} \simeq m_{proton}/2000),
  therefore, for a given temperature and density, they have much
  higher momentum p.

  In practice, the pressure provided by the /ions/ never becomes
  affected by QM directly: because of the m^{-1} term in the
  Maxwell-Boltzmann distribution, this would require densities so high
  that the ions would not exist as ions anymore. Instead the high
  density would allow for electron captures onto the protons of the
  ions turning them in neutrons (e^{-} + p \rightarrow n + \nu_{e}). As we will see this
  is what happens at the very end of the evolution of massive stars.
  However, the pressure provided by the neutrons resulting from this
  process does depend on QM effects and it is what sustains the
  structure of the neutron stars!

  Because the pressure term from electrons (which in the ideal gas EOS
  is accounted for thanks to our definition of the mean molecular
  weight \mu) changes because of QM effects first, let's now consider a
  gas made of electrons only. These particles have spin 1/2, thus they
  are fermions, and obey Eq. \ref{eq:Fermi-Dirac} and q_{s} = 2 in it
  (each quantum cell of the phase space 4\pi p^{2}dp dV can be occupied by
  2 electrons, one with spin up and one with spin down).

*** Fully degenerate electron gas

**** Non-relativistic electron gas

  In this case \varepsilon = p^{2}/2m is the energy of the electrons (still ideal
  gas), thus from the previous lecture on EOS we have:

**** Relativistic electron gas

*** Partial degeneracy

** Radiation pressure


** Partial ionization effects

** Total pressure in a generic star

#+begin_latex
\begin{equation}
P_\mathrm{tot} = P_\mathrm{gas} + P_\mathrm{rad} = \frac{\rho}{\mu m_{u}}k_{B}T +
P_{QM} + \frac{1}{3}aT^{4}  \ \ ,
\end{equation}
#+end_latex
where we have decomposed the gas pressure into a degeneracy term due
to quantum effects and a classical term.


* Homework

- Using the virial theorem, discuss which pressure term is more
  important in the total pressure as a function of the mass (and
  radius) of stars.
- Derive Chandrasekhar mass (cf. Clayton's problem 2-59)
