#+title: 400A - Virial theorem
#+author: Mathieu Renzo
#+email: mrenzo@arizona.edu

* Virial theorem
*Materials*: Chapter 2 of Onno Pols' lecture notes, Chapter 3 of
Kippenhahn's book, Sec. 1.5 of "Tapestry of Modern Astrophysics" by S.
N. Shore, pages 134-139 Clayton's book.

/The virial theorem connects gravitational physics and thermodynamics/.
It is a statistical statement on mutually interacting (e.g. because of
self-gravity!) particles, and thus it is very general. The etymology of
the name comes from "vir" which is latin for "forces".

** Complete derivation
Let's start with the most general derivation (see for example
Goldstein's classical mechanics book or Shore's Tapesty of Modern
Astrophysics Sec. 1.5). For a collection of particles with mass m_{i}, Netwon's second law states that
the change in their momentum is equal to the total force they are
subject to:

#+begin_latex
\begin{equation}
 m_{i} \ddot{r_{i}} = F_{i} \ \, .
\end{equation}
#+end_latex

Note that here r_{i} and F_{i} are vector quantities. We take the
first-order spatial moment of this distribution, which means we take
the dot product of each term by the position of the particles and sum
over all the particles. Why? The reason is /to make something like the
net potential energy appear in the second term/:

#+begin_latex
\begin{equation}
\sum_{i} m_{i}\ddot{r_{i}} \cdot r_{i} = \sum_{i} F_{i} \cdot r_{i}
\end{equation}
#+end_latex

The r.h.s. looks like a sum of work done by the total foce on each
particle: \sum_{i} F_{i} \cdot r_{i} \equiv W. This is the so called "virial",
which contains only long-range forces between the particles
(collisions cancel out in the sum). This by conservation of energy
has to be equal to the net potential energy available E_{pot}.

The l.h.s. can be re-written using the chain rule for the second time
derivative:

#+begin_latex
\begin{equation}
\sum_{i} m_{i}\ddot{r_{i}} \cdot r_{i}  = \sum_{i} \frac{1}{2} m_{i} \frac{d^{2}}{dt^{2}}r^{2} - \sum_{i} m_{i} \cdot \dot{r_{i}}^{2}
\end{equation}
#+end_latex

And now we have on the right hand side (assuming the mass of the
particles to be constant) twice the second time derivative of the moment of
inertia I = \sum_{i} m_{i} r_{i}^{2} and twice the kinetic energy E_{kin} = \sum_{i }m_{i} v_{i}^{2}/2. So
putting the r.h.s. of this last equation in the first spatial moment
of Newton's second law we obtain:

#+begin_latex
\begin{equation}
 2\mathrm{E}_\mathrm{kin}+\mathrm{E}_\mathrm{pot} = \frac{1}{2}\ddot{I}
\end{equation}
#+end_latex

This is the most-general form of the Virial theorem derived by
Clausius. In general, in the virial theorem there is a second
derivative of the moment of inertia on the r.h.s., which is often
forgotten. We did not specify almost anything about the system (see
Goldstein for a momentum-based derivation where the assumption of
constant masses m_{i} of the particles implicit in the way we wrote
Newton's second law is not even needed). It effectively says that for
a bound system of self-interacting particles, there is a limited
amount of potential energy that can be extracted, because part of the
potential will need to go into the kinetic terms and the acceleration
of the moment of inertia.

So far, this general form doesn't give us much intuition on its
meaning. We have a relation between the kinetic energy of a collection
of particles, its potential energy, and the second time-derivative of
its moment of inertia. But in the frame of the center of mass of such
collection, the kinetic energy of the particles is a measure of their
thermal energy, and this is absolutely non-trivial: why would the
thermal energy know about the potential energy! This statement is
however very general and its implication for stellar structure and
evolution are profound.

** Derivation for binary orbits

As a demonstration for the generality of the virial theorem, we can
apply it to a collection of particle with only 2 particles subject
only to the gravitational force, that is a binary system of two
point-mass stars on a Keplerian orbit!

One can write the total energy of the binary as:

#+begin_latex
\begin{equation}
E_\mathrm{tot} = \mathrm{E_\mathrm{kin}}_{1} + \mathrm{E_\mathrm{kin}}_{2} + \mathrm{E}_\mathrm{pot} \equiv \mathrm{E_\mathrm{kin}} + \mathrm{E}_\mathrm{pot}  \equiv -\frac{GM_{1}M_{2}}{2a}  \ \ ,
\end{equation}
#+end_latex
where in the last term we are using Kepler's laws. The gravitational
potential energy is E_{pot} = -GM_{1}M_{2}/a, thus making it explicit we
obtain: E_{kin} = |E_{pot}|/2. Since Keplerian orbits in Newtonian gravity are
stable, this implies that the second (and first) time-derivative of
the moment of inertia of the orbit is zero, and thus this /is/ the
virial theorem! /Keplerian binary orbits are "virialized"/.

** Derivation for stars
Let's now re-derive the Virial theorem for a star. Let's assume a
continuous description of the stellar gas, hydrostatic equilibrium and
spherical symmetry, and write explicitly the forces acting on each
shell dr of gas (cf. hydrostatic momentum balance in [[file:notes-lecture-HSE.org::*Combining the two][seen before]]):

#+begin_latex
\begin{equation}\label{eq:HSE}
\frac{dP}{dm} = -\frac{Gm}{4\pi r^{4}}
\end{equation}
#+end_latex

By analogy with what is done in the general derivation above, we want
to make the gravitational potential appear on the r.h.s., which can be
done by multiplying by 4\pi r^{3} and integrating in dm over the entire
mass of the star (from 0 to M).

#+begin_latex
\begin{equation}\label{eq:pot}
\int_{0}^{M} -\frac{Gm}{4\pi r^{4}} \times 4\pi r^{3} dm  = \int_{0}^{M} -\frac{Gm}{r}dm \equiv - \mathrm{E}_\mathrm{pot} \ \ .
\end{equation}
#+end_latex
(so that E_{pot}=|\int_{0}^{M} -Gm/r dm| >0). The l.h.s. becomes integrating per parts

#+begin_latex
\begin{equation}
\int_{0}^{M} \frac{dP}{dm} 4\pi r^{3} dm = \left[ 4\pi r^{3}P \right]^{M}_{0}- 3\int_{0}^{M}4\pi r^{2} \frac{\partial r}{\partial m} Pdm \ \ ,
\end{equation}
#+end_latex
where the first term is zero: P(M)=0 at the outer surface of the star,
and in the center r=0 by definition. For the second term, we can use
the mass continuity equation and obtain -3\int_{0}^{M} P/\rho dm, thus, putting
back the pieces together:

#+begin_latex
\begin{equation}
\int_{0}^{M }\frac{Gmdm}{r} = 3\int_{0}^{M} \frac{P}{\rho} dm \ \ .
\end{equation}
#+end_latex
Note that if we had kept a non-zero \rho \times a term in Eq. \ref{eq:HSE}, we
would again obtain a term depending on the moment of inertia and the
bulk kinetic energy of the stellar gas (see for example sec. 4.2.1 in
Shore's "Tapestry of modern astrophysics"). We have already
interpreted the r.h.s. as the gravitational potential energy
(normalized to zero at infinity) in Eq. \ref{eq:pot}. Let's interpret
the l.h.s, which in the general derivation would be part of the \sum_{i}
F\cdot r_{i} term. By dimensional analysis we know it has to have the
dimension of an energy, and in fact we know from the [[file:notes-lecture-EOS1.org::*Equation of state 1/2][EOS]] that P/\rho =
(\Gamma-1)u with \Gamma\equiv\Gamma_{1} the first adiabatic index and u specific (i.e. per
unit mass) thermal energy of the gas, so we can write:

#+begin_latex
\begin{equation}
3\int_{0}^{M} \frac{P}{\rho} dm = 3\int_{0}^{M} (\Gamma-1)u dm \ \ .
\end{equation}
#+end_latex
Assuming that \Gamma is constant throughout the star, we can take the
parenthesis out of the integral. We can define E_{int} = \int_{0}^{M} u dm
and rewrite the above as 3(\Gamma-1)E_{int}, and thus

#+begin_latex
\begin{equation}\label{eq:virial_star}
- E_\mathrm{pot} = 3(\Gamma-1)E_\mathrm{int}
\end{equation}
#+end_latex

For a monoatomic gas where each particle has 3 degrees of freedom
(motion in 3 direction, no internal degrees of freedom for
point-particles), \Gamma = 5/3, and we obtain E_{pot} = 2 E_{int} where the
internal energy is due to the thermal motion of gas, in agreement with
the general form assuming hydrostatic equilibrium.

Now lets define the total energy of the gas: E_{tot} = E_{pot} + E_{int}. For a
star to be bound, E_{tot}<0.
Because of the virial theorem in Eq. \ref{eq:virial_star}, we can
rewrite this as

#+begin_latex
\begin{equation}
\mathrm{E}_\mathrm{tot} = \mathrm{E}_\mathrm{pot}\frac{3\Gamma-4}{3(\Gamma-1)} \equiv -(3\Gamma-4)E_{int}\ \ .
\end{equation}
#+end_latex
Again, for a monoatomic gas with \Gamma=5/3 we recover E_{tot} = E_{pot}/2, the
total energy is half of the gravitational binding energy!

*** Stability criterion
From the form of E_{tot}\equiv E_{tot}(E_{int}), since E_{int} is a quantity that
is always non-negative by definition (think thermal energy!), we see
that for the star to be bound, that is E_{tot}<0, then a necessary
condition is \Gamma>4/3. One can immediately see that if \Gamma <4/3, then E_{tot}
changes sign. If E_{tot}>0 the stellar gas is unbound: the kinetic energy
is sufficient to overcome the gravitational potential and the gas will
fly out.

One can encounter cases in stellar evolution where \Gamma\le 4/3 e.g.,
because of recombination that changes the mean molecular weight, or
pair-production in the stellar interior triggering a (pulsational)
pair-instability supernova!

*** Use of gravitational energy in a star: negative heat capacity
Let's consider a star made of a perfect monoatomic gas with \Gamma=5/3.
Let's say that for some reason this star is contracting (e.g., because
it is in its formation process). Let's assume this contraction is
quasi-static, meaning that at any point in time the hydrostatic
equilibrium assumption holds, and all the bulk motion of the gas is
highly sub-sonic.

The contraction increases the gravitational potential energy E_{pot}
\prop - GM^{2}/R since M is by assumption constant and R decreases. The total
energy E_{tot} also increases, but only by half the amount that the
gravitational potential increases. The other half goes into internal
thermal energy of the gas because of the Virial theorem! This is the
limit in the amount of work that can be extracted set by the virial
theorem mentioned above.

For an ideal  gas, the internal energy is related to the
mean temperature by
#+begin_latex
\begin{equation}
E_\mathrm{int} = \frac{\# \mathrm{degrees\ of\ freedom}}{2}Nk_{B}\langle T \rangle
\end{equation}
#+end_latex
where N = M/(\mu m_{H}) is the number of particles, with \mu mean molecular
weight, <T> is the average temperature in the star, and the number of
degrees of freedom is 3 for a monoatomic gas. From the Virial theorem
it follows that:

#+begin_latex
\begin{equation}
E_\mathrm{int} = - E_\mathrm{pot}/2 \Rightarrow \frac{3}{2} \frac{M}{\mu m_{H}} k_{B}\langle T \rangle = C \frac{GM^{2}}{R} \ \ ,
\end{equation}
#+end_latex
where C = {\int_{0}^{M} Gmdm/r}/{GM^{2}/R} is a constant of O(1) that depends on
the mass distribution in the star. Thus:
#+begin_latex
\begin{equation}
\langle T \rangle = \frac{2}{3k_{B}} C \frac{GM^{}}{\mu R} \propto \frac{M}{\mu R} \ \ .
\end{equation}
#+end_latex
From this equation, several important fact follow:
- the mean temperature of a star depends only on its mass M and radius R
  (and chemical composition through \mu);
- /as a star contracts/ (R decreases at constant mass M), /the
  temperature must rise/! This, as we will see, governs the evolution
  of stars.
- A self-gravitating collection of particle with finite temperature
  must radiate away energy, thus it will lose energy. This energy
  loss, since E_{tot} = E_{pot}/2 = - CGM^{2}/2R <0 implies that R must
  decrease. But then, <T> must increase! This is the "gravothermal"
  collapse of a cloud/star. As the star loses energy (by radiating
  away some of its internal energy into photons sent through space at
  the surface), it heats up! This is why stars can be thought of
  objects with /negative/ heat capacity: it heats up as it loses energy!
  This is a property typical of self-gravitating systems only (stars
  and gravitationally bound stellar clusters) and because of the
  virial theorem it does not violate energy conservation.
- The gravothermal collapse must go on until either:
  1. an internal energy source, compensating for the surface energy loss kicks in, or
  2. the ideal gas approximation does not hold anymore.
  As we will see, both 1. and 2. occur: 1. is the typical option for
  stars using nuclear fusion as internal energy source to delay the
  collapse, and 2. is what occurs for white dwarfs, where quantum
  mechanical effects stop the collapse.

Thus, /gravity determines the evolution of a star/. It dictates that as
the star loses energy, it heats up. Because of this, at some point
nuclear fusion can occur (as we will discuss later): /stars don't
shine because they burn. Stars burn because they shine/. Without the
loss of (internal/thermal) energy by radiation they would not
contract, without contracting they would not reach temperatures high
enough to do nuclear fusion. The nuclear fusion is a /consequence/ of
the fact that stars shine, and /not the cause/.

Internal energy sources such as nuclear fusion ultimately only delay
the gravothermal collapse of the stars until either the ideal gas
approximation does not hold (for white dwarfs) or even nuclear fusion
cannot stop the collapse, and gravity wins, leading to a supernova
explosion and/or the formation of a black hole.

* Homework

- Using the virial theorem find a relation between the average sound
  speed in the star and the escape velocity
- Using the virial theorem, demonstrate that if a binary loses
  instantaneously an amount of mass greater than half the total mass
  of the binary, \Delta M \ge (M_{1}+M_{2})/2, then the orbit is unbound.
- Using the model of the 1M_{\odot} star computed earlier with MESA-web,
  use one profile file to plot \Gamma_{1}\equiv\Gamma_{1}(m). Label the age of
  the star for the corresponding profile.
