#+Title: 400A - Nuclear burning
#+author: Mathieu Renzo

* Nuclear burning in stars
*Materials:* Onno Pol's lecture notes Chapter 6.1 and 6.2, Kippenhahn
 book Chapter 9 and 18, Cox & Giuli vol. I, Chapter 17.7, [[https://ui.adsabs.harvard.edu/abs/1928Natur.122..805G/abstract][Gamow 1928]],
 [[https://ui.adsabs.harvard.edu/abs/1999RPPh...62..395A/abstract][Arnould & Takahashi 1999]], [[https://ui.adsabs.harvard.edu/abs/2011RPPh...74i6901J/abstract][Jose & Iliadis 2011]]

** Summary of where we are

We have four equations of the stellar /structure/ assuming spherical
symmetry, LTE, and hydrostatic (\partial t \equiv 0) equilibrium:

*** Mass continuity
#+begin_latex
\begin{equation}\label{eq:mass_cont}
\frac{dr}{dm} = \frac{1}{4\pi r^{2}\rho}\ \ .
\end{equation}
#+end_latex

*** Hydrostatic equilibrium
#+begin_latex
\begin{equation}\label{eq:HSE}
\frac{dP}{dm} = -\frac{Gm}{4\pi r^{4}} \ \ ,
\end{equation}
#+end_latex
which follows from the momentum continuity equation

*** Equation of state
#+begin_latex
\begin{equation}
P_\mathrm{tot} = P_\mathrm{gas} + P_\mathrm{rad} = \frac{\rho}{\mu m_{u}}k_{B}T + P_{QM} + \frac{1}{3}aT^{4}  \ \ .
\end{equation}
#+end_latex

*** Energy transport
#+begin_latex
\begin{equation}
\frac{dT}{dm} = \frac{T}{P}\frac{dP}{dm}\nabla
\end{equation}
#+end_latex
where \nabla =\partial log(T)/\partial log(P) is the local temperature gradient, equal to
the radiative gradient in stably stratified regions:
#+begin_latex
\begin{equation}
\nabla_\mathrm{rad} = \frac{3 P}{14\pi acGm T^{4}}\kappa L
\end{equation}
#+end_latex
with \kappa = (1/\kappa_{rad} + 1/\kappa_{cond})^{-1} the combination "in parallel" of the
radiative and conductive opacity (assumed to be known from atomic
physics), and \nabla \equiv \nabla_{ad} the adiabatic gradient (within \sim10^{-7-8}
precision) for convective regions. We also have a criterion
(Schwarzschild criterion) to determine which region is which.

*** Energy conservation
#+begin_latex
\begin{equation}
\frac{dL}{dm} = \varepsilon_\mathrm{nuc} -\varepsilon_{\nu} + \varepsilon_\mathrm{grav} \ \ .
\end{equation}
#+end_latex

with \varepsilon_{grav} = T\partial s/\partial t the change in internal energy.

** The next step

With all the equations above we almost have a complete set of solvable
differential equations. What is left to discuss is the specific energy
generation per unit time \varepsilon_{nuc} due to nuclear burning and the specific
energy loss \varepsilon_{\nu} due to neutrino losses.

In doing so, we will introduce the only time-dependent equation: as
nuclear burning proceeds, the chemical composition changes, on a
timescale that we will see is extremely long compared to the thermal
and dynamical timescales.

** Energy generation as a self-regulating process

We have seen in the [[./notes-lecture-VirTheo.org][virial theorem lecture]] that one can derive from
first principle that stars have a "negative heat capacity" and obtain
a scaling between mass, radius and average temperature:
#+begin_latex
\begin{equation}
\langle T \rangle = \frac{2\mu m_{u}}{3} C \frac{GM^{}}{R} \propto \frac{\mu M}{R} \ \ .
\end{equation}
#+end_latex
As the star loses energy at the surface because of its luminosity L it
must contract (lower its gravitational potential energy), leading to
an increase in T. For the Sun this would go on for \sim 15 Myrs before it
runs out of all of its internal energy, which is way too short a
timescale to explain many Earthly observables.

We know this must stop either because the ideal gas EOS does not work
(QM effects \rightarrow degeneracy pressure \rightarrow white dwarfs), or because some
other energy source intervenes, balancing out the energy losses at the
surface. /Stars don't shine because they burn, stars burn because they
shine/.

Initially, people considered radioactivity as a possible energy
source, but this was shown very quickly to be insufficient. It took
major advances in quantum mechanics and their application to atomic
and nuclear theory to work out in the late 1930s that the energy
source is nuclear burning, a result obtained by [[https://en.wikipedia.org/wiki/Hans_Bethe][Hans Bethe]] and
collaborators.

In a sense, you can think  of a star as an /inertial confinement nuclear
reactor/ where the confinement is provided by the self-gravity. This
also implies that nuclear burning in a star is a /self-regulating/
process: because nuclear reactions are a consequence of the energy
losses, during long-lived equilibrium phases of the stellar life, they
produce just enough energy to balance the losses! In other words,
L_{nuc} = L ( + L_{\nu}).

If a star were to not produce enough energy to verify that (i.e.,
L>L_{nuc}), then it will lose too much energy, meaning it will contract,
and increase it's temperature because of the virial theorem, which in
turn regulates the energy generation by nuclear reactions (as we will
see in a moment), until L_{nuc} reaches L.
Viceversa, if L_{nuc} > L for some reason (e.g., there is a thermonuclear
explosion in the star), than the extra energy release will cause an
expansion of the star and by the virial theorem lower the mean
temperature until L_{nuc} = L.

** The nuclear timescale

Naturally, nuclear energy generation consumes nuclear fuel: to provide
L_{nuc} the composition of the star slightly changes in time. This drives
the /evolution/ of star.

We can estimate the timescale for this assuming the star is in
gravothermal equilibrium, so L=L_{nuc}. The /nuclear timescale/ is the time
it takes to lose the energy generated by nuclear reactions:

#+begin_latex
\begin{equation}
\tau_\mathrm{nuc} = \phi f_{burn} \frac{Mc^{2}}{L_{nuc}} \equiv \phi f_{burn} \frac{Mc^{2}}{L_{}} \ \ ,
\end{equation}
#+end_latex

where \phi is the fraction of rest mass of nuclei converted in energy by
nuclear burning, f_{burn} is the fraction of the stellar mass M that is
affected by burning (we need a stellar model to estimate that).

For the Sun, f_{burn} \simeq 0.1 from detailed models (as you can verify
with your =MESA-web= model!), and \phi depends on the nuclear physics
details that we will discuss today, but for hydrogen fusion it is
\sim0.007. Plugging in these numbers and M_{\odot} and L_{\odot} we get for the
nuclear timescale:

#+begin_latex
\begin{equation}\label{eq:tau_nuc_scaling}
\tau_\mathrm{nuc} \simeq 10^{10} \frac{M}{M_{\odot}} \frac{L}{L_{\odot}} \ \ mathrm{yr} \ \ .
\end{equation}
#+end_latex

So we now have estimates that allow us to see the complete
ordering for the main /global/ timescales for stellar evolution:

#+begin_latex
\begin{equation}\label{eq:timescale_ordering}
\tau_\mathrm{ff} \ll \tau_\mathrm{KH} \ll \tau_\mathrm{nuc} \ \ .
\end{equation}
#+end_latex

Moreover, Eq. \ref{eq:tau_nuc_scaling} shows that when accounting for
nuclear energy generation (which we have implicitly assumed here to
give a value of \phi), the nuclear timescale matches the timescale found
from geological evidence on Earth, and the ordering \ref{eq:timescale_ordering}
tells us that the evolution of the Sun is on a very slow timescale
compared to thermal and dynamical timescale, validating the
assumptions we made so far to derive the equations for stellar
/structure/ and allowing for a /quasi-static/ approximation to deal with
the stellar /evolution/.

Let's now dive into the details of the nuclear physics that allow for
nuclear burning.
