#+title: 400A - EOS (polytropic & ideal gas)
#+author: Mathieu Renzo
#+email: mrenzo@arizona.edu

* Equation of state 1/2
*Materials*: Chapter 3 of Onno Pols' lecture notes, Sec. 2.2 of
Kippenhahn's book, Sec. 2-4 of Clayton's book.

** Summary of where we are

We have introduced now two equations of the stellar structure (*N.B.:*
at the end of the course we'll need 5 to close the system and get a
solvable model), and we know we can write them using the Lagrangian
mass coordinate as independent variable. But to reason conceptually
about the problem, we can stick to writing them as a function of r:

*Mass conservation:*
#+begin_latex
\begin{equation}
dm = 4\pi \rho r^{2} dr \ \ .
\end{equation}
#+end_latex

*Hydrostatic equilibrium:*
#+begin_latex
\begin{equation}
\frac{dP}{dr} = -\frac{Gm}{r^{2}}\rho \ \ ,
\end{equation}
#+end_latex

These two equations have as variables m\equiv m(r) (or equivalently r\equiv
r(m)), P and \rho. So clearly we cannot yet solve them, we need some
relation between the pressure and the density - a so-called equation
of state (EOS).

The aim of this lecture is to introduce first simple EOS which do not
introduce any other variables, and then go over a more appropriate
EOS, the ideal gas EOS, which is a good approximation for most stars.
We will see other EOS (for degenerate or radiation-dominated gas) in a
[[./notes-lecture-EOS2][future lecture]].

** Global and local thermal equilibrium
Before we get into the EOS though, we have to ask ourselves whether we
can use thermodynamics/statistical mechanics to try to find some
relationship between P, \rho (and maybe other thermodynamic quantities
will come in).

Thermal equilibrium means by definition that all the particles in a
system (including photons, if there is radiation) have the same
temperature T, and their velocity distribution are described by a
Maxwellian (for particles) and the black-body spectrum (for
radiation). This situation can only be achieved if there are
sufficient interactions so each particle can exchange energy with the
others (collisions among particles, and scattering/absorption for
photon-particles interactions).

:Questions:
- *Q*: are stars in global thermal equilibrium? If they were, they would
  have a single temperature throughout the star, does this sound
  realistic?
:end:

*Stars are not in global thermal equilibrium*. They are in "gravothermal
equilibrium": the hydrostatic requirement and the self-gravity
determine the thermal state of each layer so that the pressure
gradient can balance gravity.

However, /locally/, we can still assume that there are stellar layers
with a thickness dr\ll R that are in thermal equilibrium. For this to
happen, this layer needs still to be much larger than the
mean-free-path for particle-particle and particle-photon interactions.
Let's consider the latter first:

#+begin_latex
\begin{equation}
\lambda_{\gamma} = \frac{1}{n\sigma} \equiv \frac{1}{\kappa\rho} \ \ ,
\end{equation}
#+end_latex

where n is the number density of particles ([n] = cm^{-3}) and \sigma ([\sigma] =
cm^{2}) is the interaction cross section, or equivalently, \rho is the mass
density (appearing in the two equations), and \kappa is the "opacity",
which is a way to measure the probability of a photon to interact with
a certain amount of mass.

:Questions:
- *Q*: what are the units of \kappa? How can we interpret it?
:end:

Let's for simplicity assume that a star is all made of hydrogen (a
result first derived ~100 years ago by Cecilia Payne in her PhD thesis
in 1925). Let's also assume that it is fully ionized (i.e., protons
and electrons are separated from each other). The very minimum opacity
in this case is given by scattering of photons onto the electrons and
is: \kappa = 0.2(1+X) cm^{2} g^{-1}, where X is the mass fraction hydrogen, so
for our rough approximation, \kappa\simeq0.4. The average density of the Sun
(which you calculated for the last homework) is \rho_{\odot, avg}\simeq1.4 g
cm^{-3}, therefore \lambda_{\gamma} \simeq 2 cm. The mean-free-path for
particle-particle interactions is much smaller (because the cross
section \sigma is larger), so we can conservatively ask what is the
temperature variation across this distance:

\Delta T \simeq \lambda_{\gamma} dT/dr \le \lambda_{\gamma} T_{center}/R

(where we neglect T_{surface} because we expect it much lower than
T_{center}, since we already know P_{center} \gg P_{surface}). For the Sun we
will see that we can estimate T_{center}\simeq 10^{9} K, and we know R_{\odot},
so \Delta T\simeq 10^{-4} K \ll T_{surf} \ll T_{center}.

Thus, we can define layers of the star with \lambda_{gamma} \ll dr \ll R where
locally the temperature variation across the layer is negligible, and
the assumption of /local thermal equilibrium/ (LTE) holds well. (*N.B.:* you can
revise this a posteriori once we have an EOS!)

This may not be true close to the surface, where \lambda_{\gamma} progressively
increases (because \rho decreases). There we may need to care about the
wavelength or frequency dependance of the cross section \sigma\equiv\sigma(\nu) and
thus the mean free path: a star has a different "surface" for
different photon frequencies! In those layers, the assumption of LTE
does not work.

As long as we discuss regions of the star with a thickness large
w.r.t. \lambda_{\gamma} but small enough that the T variation across them, we
can use thermodynamics!

Also, as we have seen before, the stars are usually in equilibrium and
change very slowly. Any /local/ thermal imbalance will be restored on
the /local/ thermal timescale, which can be estimate in multiple ways,
but it is usually very short compared to the star evolutionary
timescale (we will see this in more detail later). Thus the assumption
of LTE holds locally (as the L indicates) at any time!

** Polytropic EOS
Polytropic EOS as a special case of /barotropic/ EOS, which are all the
EOSs for which /the density depends only on the pressure/:
\rho\equiv\rho(P). These have applications beyond stellar physics (e.g., for
atmospheric physics). A polytropic EOS is thus a barotropic EOS where
the \rho\equiv\rho(P) is in the form of a powerlaw, although usually written in
this form:

#+begin_latex
\begin{equation}
P = K\rho^{\Gamma} \equiv K\rho^{1+1/n}\ \ ,
\end{equation}
#+end_latex

where K is a constant, and by definition \Gamma=\partial ln P /\partial ln \rho = 1+1/n.
Such a form of the EOS may be


** Kelvin-Helmholtz timescale
This is by definition the timescale it takes a star to radiate away
all its internal energy at a constant rate in absence of any other
energy sources. Let's call L the "luminosity of the star", that is the
rate at which is loses energy from radiating away photons at its
surface. Note that L has the units of power:

[L] = [E]/[t]

Then by definition:
#+begin_latex
\begin{equation}\label{eq:tau_KH}
\tau_\mathrm{KH} = \frac{\mathrm{E}_\mathrm{int}}{L} \equiv
\frac{\mathrm{E}_\mathrm{pot}}{2L} \simeq \frac{GM^{2}}{2RL} \ \ ,
\end{equation}
#+end_latex
where we have used the virial theorem and set C\simeq1. We can scale all
the quantities to Solar values and obtain:
#+begin_latex
\begin{equation}
\tau_{KH} \simeq 10^{7} \mathrm{years} \times \left(\frac{M}{M_{\odot}}\right)^{2} \left(\frac{R}{R_{\odot}}\right)^{-1 }\left(\frac{L}{L_{\odot}}\right)^{-1} \ \ .
\end{equation}
#+end_latex
Clearly \tau_{KH} \gg \tau_{ff}, and also \gg {human timescales}: it is hard to
get direct observational evidence that stars are in thermal
equilibrium. In fact, the name of this timescale comes from proposals
in the late 19^{th} century by Kelvin and Helmholtz that the Sun may be
out of thermal equilibrium and contracting, meaning it would have a
lifetime of the order of \sim 10 million years -- this was in contrast
with geological evidence (and with the timescale necessary for
Darwinian evolution), leading to a great debate that was ultimately
settled with the discovery of nuclear energy as a potential source of
energy in the 1930s (by primarily Bethe and collaborators), see G.
Shaviv "Life of stars" for a detailed discussion.

:Question:
- *Q*: A star may lose energy also by means other than photons,
  especially neutrinos. If such energy losses are important, how can
  we modify Eq. \ref{eq:tau_KH}?
:end:


** Ideal gas

*** The mean molecular weight
