#+title: 400A - Introduction
#+author: Mathieu Renzo
#+email: mrenzo@arizona.edu

* Introduction to the course
*Materials*: chapter 1 of Onno Pols' lecture notes.

** Aim
- Discuss [[./syllabus.org][syllabus]] and learning outcomes
- Go over some basics (magnitudes, parallaxes, solar quantities)
- Discuss project, show list
- Discuss expectations and grading rubrics for course and project

** Aim of the course

*To understand the structure and evolution of stars and their
observational properties using known laws of physics.*

** What is a star?
- Historical definition: /flickering light source in the sky with no
  intrinsic motion/ (where flickering excludes planets, and no
  intrinsic motion excludes planets /and/ other solar system objects
  such as comets and asteroids).
- More modern definition: /self-gravitating amount of gas that at some
  point is sufficiently hot for nuclear fusion/.

Note that the requirement of nuclear fusion is *extremely new*: only
about 100 years old! A lot can be learned about stars without knowing
anything about nuclear fusion, which we will treat, but much later in
the course.

** What determines the properties of a (single) star?
- *Mass*
- Chemical composition
- Rotation

:Questions:
- *Q*: what is a star made of? Can you think of a star made of something
  else? Mention Cecilia Payne-Gaposchkin.
:end:

** Observations
- Photometry
- Spectroscopy
- Astrometry
- Asteroseismology
- Neutrinos

*** Parallax
In astrophysics (and in stellar physics in particular) we still use
quantities and units that have as only justification historical
reasons.

The yearly apparent motion on the sky of stars (w.r.t. to father stars
that are too far to exhibit this behavior) due to the orbit of the
Earth around the Sun is called /parallax/. A commonly used unit of
distance in astronomy is the /parsec/ =  distance of a star with a
parallax of one arcsecond:

#+begin_latex
\begin{equation}
1 pc \simeq 3\times10^{18} cm \simeq 2\times 10^{5} AU
\end{equation}
#+end_latex

This is a measure of the stars distance that can be used for stars
with relatively small distances to the Solar system.

*** Magnitudes
The magnitude scale is a logarithmic scale first introduces by
Hipparcos, who clearly was only able to do naked-eye observations.
This explains why a logarithmic scale: the sensory responses are often
logarithmic (see [[https://en.m.wikipedia.org/wiki/Weber%E2%80%93Fechner_law][Weber-Fechner's law]]). The magnitude scale was
formalized by [[https://ui.adsabs.harvard.edu/abs/1856MNRAS..17...12P/abstract][Pogson 1856]].

The magnitudes measure the monochromatic energy flux from a point-like
source (like a distant star) and it is a differential measure relative
to some standard source. Hipparcos was comparing the visual brightness
of various stars visible in the sky. This is still the basis of (some)
magnitude systems.  In reality typically magnitudes are provided
integrating over a range of frequencies (photometry!) accounting for
the response of a filter as a function of wavelength T(\lambda):

#+begin_latex
\begin{equation}
m = -2.5\log_{10}\left(\frac{\int T(\lambda)F_{\lambda}d\lambda}{\int
T(\lambda) d\lambda}\right) + m_{0} \ \ ,
\end{equation}
#+end_latex

where m_{0} is the reference magnitude, F_{\lambda} is the monochromatic
flux of the source, and the factor of -2.5 is chosen so that the
magnitudes measured this way roughly agree with Hipparcos'. Thus, an
increase of 5 magnitudes corresponds to an increase in flux of a
factor of 100.

The /bolometric/ magnitude is the magnitude across all wavelengths for
an idealized perfect detector (T(\lambda) = 1 \forall \lambda). If the distance of a
source is known, we can then infer its intrinsic luminosity from this.

The /apparent/ magnitude is a measure of the actual photon flux received
from a source (e.g., a star) on Earth, but that of course depends on
how far the source is from Earth (a candle in your hand has a higher
apparent magnitude than Betelgeuse in the sky!). Therefore, astronomer
also introduced the /absolute/ magnitude as the apparent magnitude a
star would have if it were at a distance of 10pc from the Sun, thus
the relation between apparent magnitude m and absolute magnitude M is

#+begin_latex
\begin{equation}\label{eq:abs_magn}
M - m = -2.5\log_{10}\left[\left(\frac{D}{10\mathrm{pc}}\right)^{2}\right] \ \,
\end{equation}
#+end_latex

where D is the distance, and it is assumed there is no absorption of
light by the interstellar material.

For the reference magnitude m_{0} there are multiple choices (and there
are many different magnitude systems because of the T(\lambda) and m_{0}
choices!). For instance, typically the star Vega (\alpha Lyrae) is used as
a standard and by definition its magnitude in U, B, and V band in the
Vega-based magnitude system is zero. So for magnitude M=0 we have a
specific (i.e., per unit frequency) radiative energy flux of 3.5\times10^{-20}
erg cm^{-2} s^{-1} Hz^{-1} corresponding to a photon flux of N_{\lambda} \simeq
10^{3} photons cm^{-2} s^{-1} Å^{-1} for the visual band.

:Questions:
- *Q*: why the square within the argument of the logarithm in Eq.
  \ref{eq:abs_magn}?
:end:


** Relevant physical scales
The star we can observe best is the closest one, the Sun (\odot), so a
lot of quantities are scaled to those of the Sun in stellar physics
and in astronomy more generally.

*** Solar radius: R_{\odot} = 6.957\times 10^{10} cm \simeq 7\times10^{10} cm \simeq 10^{11} cm
*** Solar mass: M_{\odot} = 1.98\times10^{33} g\simeq 2\times10^{33} g
*** Solar luminosity: L_{\odot} = 3.82\times10^{33} erg s^{-1} \simeq 2\times M_{\odot} in cgs units!
This may be one of the reasons why we still use =cgs= in astronomy,
the other one being that the constants in electromagnetism are a
bit simpler.
*** Solar effective temperature: T_{\odot}\simeq 6000K
This is the "effective temperature" of the Sun, which we will discuss
in the [[file:notes-lecture-CMD-HRD.org][next lecture]]. It is an approximation for the temperature of the
surface below which the radiation field is isotropic - that is the
stellar interior - and above which there is a net radial flux of
photons - that is the stellar atmosphere (but photons can still move
around in any direction, it's just on average there are more moving in
the positive r direction). Stars don't really have a well defined
"surface" and their spectra form in the atmospheric layers.

*** Solar metallicity: Z_{\odot} = 0.0146 \simeq 0.02 (older but still widely used value)
The "metallicity" is the fraction by mass of gas that is /not/ hydrogen
nor helium. This includes many elements (e.g., C, N, O, Si) that a
chemist would not call "metals".

Often, for lack of better knowledge available, we assume that the
distribution of metals scales with the Solar distribution, sometimes
allowing for enhancement of \alpha particles (e.g., carbon, oxygen, neon,
and all other elements that can approximately be thought of as N \alpha
particles bound together where \alpha particle = nucleus of helium 4).

A common notation is also [X/H] = log_{10}[(n_{X}/n_{H})/(n_{X}/n_{H})_{\odot}], and
[Fe/H] can be used as a proxy for the metallicity.


*** Lifetimes: ~3 Myr to \gg age of the Universe (\simeq 13.7 Gyr)
:Questions:
 - *Q*: How old is the Sun? How long will it live? How do we know?
:end:
** Discuss projects

- Projects will cover topics that are important and or timely, but
  hard to fit in the main body of the course
- Occasion for you to dig deeper and teach to your peers
- You should look over the [[file:projects.org::*List of possible projects/presentations][proposed project]], and within a week give us
  a ranked list of 5 projects you'd like to do.
- Look over also [[file:projects.org::*Grading][how the grading will work]].
- We will assign to each a project trying to maximize happiness, and
  for each project we will assign two peer referees.

* Homework

- Calculate the average density of the Sun and compare it with the
density of something familiar on Earth.
- start looking over the [[file:projects.org::*List of possible projects/presentations][list of final project]], you will need to
provide us with a ranked list of 5 preferences. Feel free to search
the web/literature to decide. Based on this list, we will try to
assign projects and peer-referee, but it may not be possible to
satisfy everyone. If you want, feel free to come up with different
subjects related to stellar physics as well to propose, but you need
to talk to us to get them approved before they can be on your list!
