#+title: 400A - EOS (degenerate)
#+author: Mathieu Renzo
#+email: mrenzo@arizona.edu

* Equation of state 2/2
*Materials*: Chapter 3 of Onno Pols' lecture notes, Chapter 15 and 16 of
Kippenhahn's book.

In the [[./notes-lecture-EOS1.org][previous lecture on EOS]] we have dealt with a classical,
non-relativistic, ideal gas. This is an accurate description of the
stellar gas in most, but importantly not /all/ the physical cases.

We will consider now cases that don't verify the hypothesis we took
previously and discuss briefly some stars for which we need to go
beyond those.

** Quantum-mechanical effects

A star is "big", why do we need to care about quantum mechanics (QM)?
Besides its central role in allowing for nuclear burning, [[file:materials/nuclear_reaction_rates.pdf][which we
will see later]], QM effects can matter also at extremely low
temperatures and/or high densities, which can be encountered in
stellar physics.


*** Non-relativistic gas

*** Relativistic gas

** Radiation pressure

** Total pressure in a generic star

#+begin_latex
\begin{equation}
P_\mathrm{tot} = P_\mathrm{gas} + P_\mathrm{rad} = \frac{\rho}{\mu m_{u}}k_{B}T +
P_{QM} + \frac{1}{3}aT^{4}  \ \ ,
\end{equation}
#+end_latex
where we have decomposed the gas pressure into a degeneracy term due
to quantum effects and a classical term.


* Homework

Derive Chandrasekhar mass?

- Using the virial theorem, discuss which pressure term is more
  important in the total pressure as a function of the mass (and
  radius) of stars.
