#+title: 400A - Energy transport
#+author: Mathieu Renzo
#+email: mrenzo@arizona.edu

* Energy transport in stars
*Materials*: Chapters 3 and 5 of Onno Pols' lecture notes, chapter 5 of
Kippenhan & Weigert's book.

** Summary of where we are

*Mass conservation:*
#+begin_latex
\begin{equation}\label{eq:mass_cont}
dm = 4\pi \rho r^{2} dr \ \ .
\end{equation}
#+end_latex

*Hydrostatic equilibrium:*
#+begin_latex
\begin{equation}\label{eq:HSE}
\frac{dP}{dr} = -\frac{Gm}{r^{2}}\rho \ \ ,
\end{equation}
#+end_latex


*Equation of state:*
#+begin_latex
\begin{equation}\label{eq:EOS}
P \equiv P(\rho, \mu, T) \ \ .
\end{equation}
#+end_latex

These three equations have as variables m \equiv m(r) (or equivalently r\equiv
r(m)), P, \rho, and T. By adding an EOS to relate P and \rho (and the
composition of the star which enters in the mean molecular weight \mu),
in the general case, we have also added a new variable T, so the
system is not close again, and we need to look for one more equation
to be able to solve it!

** Energy flow in stars

To find another equation, we can consider how energy flows in a star.
We have already seen that the surface temperature (e.g., of the Sun),
and the average temperature (estimated using the [[file:notes-lecture-VirTheo.org::+title: 400A - Virial theorem][virial theorem]]) are
/not/ the same, so we know that the star is /not/ in global thermal
equilibrium. We also know, from similar arguments, that the average
temperature is higher than the surface temperature, so there should be
an energy flow from the interior outwards.

This energy flow can occur in three forms in a star:
1. *Diffusion*: thermal energy can be moved by the random motion of
   particles. This is often the dominant energy transport mechanism in
   a star -- unless for some reason it is insufficient. The diffusion
   of energy can be:
   - *Radiative*, if the particles carrying the energy through their
     random motion are photons
   - *Conductive*: if it is the thermal motion of gas particles
     (typically electrons, unless you are in a neutron star) that
     carries the energy
2. *Convection*: in this case thermal energy is transported by bulk
   motion of matter. This occurs as a *thermal* instability if the other
   means of energy transport are insufficient to carry the energy flux
   required by the local stellar structure, and it will be the topic
   of a [[https://www.as.arizona.edu/~mrenzo/materials/Convection.pdf][future lecture]].
3. *Neutrino losses*: except for collapsing iron cores and neutron
   stars, the stellar gas is transparent to neutrinos. As soon as one
   is produced, it can free stream out of the star carrying away
   energy effectively instantaneously.

The next /two/ stellar structure equations to add to our system will
come from combining all of these together.

** Diffusion processes
In general, the "diffusion approximation" is useful to describe the
net flux of "something" when the average path of the carrier of said
"something" is small compared to the lengthscale over which the
"something" is transported.

In this approximation, the net flux of this "something" is related to
the density of "something" by

#+begin_latex
\begin{equation}\label{eq:diff}
\mathbf{J} = - D\nabla n \ \ ,
\end{equation}
#+end_latex
where J is the flux (which is in general a vector quantity), D is the
so called "diffusion coefficient", and \nabla n is the gradient of the
volumetric density of the "something" we are considering. The negative
sign appears because the flux is opposite to the gradient ("something"
flows from where there is a lot to where there is less!). By
dimensional analysis, regardless of what "something" is (and what are
its dimensions), you can see that:
- [J] = [something]/(L^{2}t) with L length dimension and t time;
- [\nabla] \equiv [d/dx] = 1/L;
- [n] = [something]/L^{3}

Therefore, the diffusion coefficient has the dimensions of [D] = L^{2}/t
\equiv v \times L, so we can expect D to be proportional to the average velocity
of the "something" that is diffusing times the length scale for the
motion of this something (which by hypothesis is small compared to the
length scale over which we want to study the motion of this
"something"). In fact this is almost correct!

To get the correct pre-factor, let's say "something" are particles
moving in 3 dimensions and focus on one direction, say z. If all these
particles have a mean free path \ell and an average velocity v, then the
number that crosses a given coordinate z with a positive \delta z as a
function of time is:
#+begin_latex
\begin{equation}
\frac{dN}{dt}(z) =\frac{1}{2} n \frac{1}{3}v \ \ ,
\end{equation}
#+end_latex
where the first 1/2 factor comes from the fact that their motion is
random, so half the particles have negative \delta z and half have a
positive one, and we just want to count the latter, and the factor of
1/3 in front of their average velocity comes from the fact that the
motion is isotropic (see [[file:notes-lecture-EOS1.org::*Ideal gas][derivation of the pressure]]).

If there is a gradient \partial n /\partial z of particles along the z direction,
the particles moving with positive \delta z  come from n(z-\ell)
while those moving with the negative \delta z  come from n(z+\ell), so the net
flux across z is

#+begin_latex
\begin{equation}
J = \frac{dN}{dt}(z-\ell) -\frac{dN}{dt}(z+\ell) = \frac{1}{6}v\left(n(z-\ell)-n(z+\ell)\right)=\frac{1}{6}v\left(-2\ell\frac{\partial n}{\partial z}\right) = -\frac{1}{3}v\ell\frac{\partial n}{\partial z} \ \ .
\end{equation}
#+end_latex

Eq. \ref{eq:diff} is the generalization in 3 dimensions of the above,
where \nabla = (\partial_{x}, \partial_{y}, \partial_{z}) for Cartesian coordinates, and
D=v\ell/3.

*** Energy transport by radiative diffusion
We have already calculated that [[file:notes-lecture-EOS1.org::*Global and local thermal equilibrium][mean free path for photons]] and
estimated that it is very small compared to the typical size of stars.
Therefore, we can treat the energy transport by photons in the
diffusion approximation.

*N.B.*: if the star were a perfect black body, there would not be any
transport of energy by photons, because by definition the radiation
field would be isotropic, and the gradient of photon energy density
would be zero! In reality, we have already seen that stars are /not/
black bodies at the surface (in the atmospheric layers where \ell_{\gamma}
is not small) and neither they are in the interior because there is a
small deviation from LTE of the order of \ell_{\gamma} dT/dr~10^{-11}. While
this is a small enough deviation that we can assume LTE to write down
an EOS, it is also big enough to introduce a non-negligible flux of
energy in the stars!

If the "something" that we are considering in our diffusion equation
is energy, then in Eq. \ref{eq:diff} J\rightarrow F is an energy flux, and n\rightarrow u
is the energy density. Moreover, in the diffusion coefficient D the
mean velocity of photons is v\rightarrow c, and we have already written \ell_{\gamma}
= 1/\kappa\rho as a function of \rho.

Thus, the radiative diffusion equation is
#+begin_latex
\begin{equation}
F = - \frac{1}{3}\frac{c}{\kappa\rho}\frac{du}{dr} \ \ ,
\end{equation}
#+end_latex
where we use the spherical symmetry of the problem to explicit the
gradient and turn it into a total derivative. The radiation energy
density is u=aT^{4}. We can then explicit these into our equation
obtaining an equation for the temperature gradient. This is a /local/
quantity and it is valid in a region of the star where the dominant
energy transport is radiative diffusion only:

#+begin_latex
\begin{equation}
\frac{dT}{dr} = -\frac{3}{4ac}\frac{\rho}{T^{3}}\kappa F \ \ .
\end{equation}
#+end_latex
/In a radiative region the temperature is proportional to the opacity
\kappa times the radiative energy flux F/: dT/dr\propto \kappa F.

We can further rewrite the flux F as the local luminosity L_{rad}/(4\pi
r^{2}). This introduces the /local/ luminosity L_{rad}\equiv L_{rad}(r) which is
the rate (that is per unit time) at which radiation transports energy
through a surface of radius r within the star.

*N.B.:* If radiative energy transport is the *only* energy transport
mechanism at radius r, then L_{rad}(r)\equiv L(r) where L(r) is the /total/
luminosity. This is in general not true because of the contribution
by neutrinos and convection: L(r) = L_{rad} + L_{\nu} +L_{conv}.

#+begin_latex
\begin{equation}\label{eq:diff}
\frac{dT}{dr} = -\frac{3}{16 \pi ac}\frac{\rho\kappa}{r^{2}}\frac{L_{rad}}{T^{3}} \ \ .
\end{equation}
#+end_latex

This is, for the case of radiative energy transport only, the extra
differential equation relating T and \rho, but unfortunately it also
brings in a new variable, the local radiative luminosity L_{rad}.

*N.B.:* Yes, we are introducing yet another variable \kappa here, but
fortunately for us, as [[file:notes-lecture-kappa.org][we will see]], this factor is determined by
atomic physics. While this is an active topic of research (including
classified research for military purposes), for stellar physics
application we have lookup tables for \kappa\equiv\kappa(T,\rho), and thus we will not
count it as a new variable after discussing the physics it represents.

Because of the assumption underpinning the diffusion approximation,
this is /not/ the right equation whenever \ell_{\lambda} is not negligible
compared to the scale over which one wants to consider the gradient:
in the stellar atmosphere we need a more detailed approach requiring
to treat the radiative transfer.

Now, before looking at the equation for L_{rad}, it is useful to consider
next the case where energy is carried not by photons, but by the local
motion of particles, that is *conduction*.

*** Energy transport by conduction
Energy transport by conduction is not limited to stars. For example a
piece of metal left half in the Arizona Sun and half in the shade. The
thermal motion of particles (atoms, electrons, ions) carries energy
from the hotter parts to the colder ones.

Actually, it is important only in certain kind of stars. To
demonstrate this, we can consider the diffusion coefficient D=v\ell/3 and
compare it to the radiative diffusion coefficient D_{rad} = c\ell_{\gamma}/3
=c/(3\kappa\rho). The latter is going to be in general much larger because c\gg
v with v thermal velocity of the particles (v^{2}\simeq 2k_{b}<T>/m)


** Local energy conservation


* Homework
- estimate the thermal velocity of particles (electrons and protons)
  using the Virial theorem to estimate the temperature and compare it
  to the speed of light. Compare the diffusion coefficient for
  radiative diffusion and conduction and derive the average density
  above which conduction can start to compete with radiative
  diffusion. For a star of 1M_{\odot}, to which radius does that correspond?
