#+title: 400A - EOS (polytropic & ideal gas)
#+author: Mathieu Renzo
#+email: mrenzo@arizona.edu

* Equation of state 1/2
*Materials*: Chapter 3 of Onno Pols' lecture notes, Sec. 2.2 of
Kippenhahn's book, Sec. 2-4 of Clayton's book.

** Summary of where we are

We have introduced now two equations of the stellar structure (*N.B.:*
at the end of the course we'll need 5 to close the system and get a
solvable model), and we know we can write them using the Lagrangian
mass coordinate as independent variable. But to reason conceptually
about the problem, we can stick to writing them as a function of r:

*Mass conservation:*
#+begin_latex
\begin{equation}\label{eq:mass_cont}
dm = 4\pi \rho r^{2} dr \ \ .
\end{equation}
#+end_latex

*Hydrostatic equilibrium:*
#+begin_latex
\begin{equation}\label{eq:HSE}
\frac{dP}{dr} = -\frac{Gm}{r^{2}}\rho \ \ ,
\end{equation}
#+end_latex

These two equations have as variables m\equiv m(r) (or equivalently r\equiv
r(m)), P and \rho. So clearly we cannot yet solve them, we need some
relation between the pressure and the density - a so-called equation
of state (EOS).

In general this is a relation between the /local/ value of pressure P,
density \rho, and temperature T, which may also depend on the
composition, that is the ensemble of fraction by mass of elements (X_{i}
= mass of i-th element/total mass):

#+begin_latex
\begin{equation}\label{eq:general_EOS}
P\equiv P(\rho, T, \{X_{i}\})
\end{equation}
#+end_latex

For a given composition {X_{i}}, given two out of three between P, \rho, T,
one can obtain the third using the EOS.

The aim of this lecture is to introduce first simple EOS which do not
introduce any other variables (so independent of T), and then go over
a more appropriate EOS which is a good approximation for most stars,
the ideal gas EOS. We will see other EOS (for degenerate or
radiation-dominated gas) in a [[./notes-lecture-EOS2][future lecture]].

** Global and local thermal equilibrium
Before we get into the EOS though, we have to ask ourselves whether we
can use thermodynamics/statistical mechanics to describe the
/microscopic/ properties of the stellar gas and find some relationship
between P, \rho (and maybe other thermodynamic quantities will come in).

Thermal equilibrium means by definition that all the particles in a
system (including photons, if there is radiation) have the same
temperature T, and their velocity distribution are described by a
Maxwellian (for particles) and the black-body spectrum (for
radiation). This situation can only be achieved if there are
sufficient interactions so each particle can exchange energy with the
others (collisions among particles, and scattering/absorption for
photon-particles interactions).

:Questions:
- *Q*: are stars in global thermal equilibrium? If they were, they would
  have a single temperature throughout the star, does this sound
  realistic?
:end:

*Stars are not in global thermal equilibrium*. They are in "gravothermal
equilibrium": the hydrostatic requirement and the self-gravity
determine the thermal state of each layer so that the pressure
gradient can balance gravity.

However, /locally/, we can still assume that there are stellar layers
with a thickness dr\ll R that are in thermal equilibrium. For this to
happen, this layer needs still to be much larger than the
mean-free-path for particle-particle and particle-photon interactions.
Let's consider the latter first:

#+begin_latex
\begin{equation}
\lambda_{\gamma} = \frac{1}{n\sigma} \equiv \frac{1}{\kappa\rho} \ \ ,
\end{equation}
#+end_latex

where n is the number density of particles ([n] = cm^{-3}) and \sigma ([\sigma] =
cm^{2}) is the interaction cross section, or equivalently, \rho is the mass
density (appearing in the two equations), and \kappa is the "opacity",
which is a way to measure the probability of a photon to interact with
a certain amount of mass.

:Questions:
- *Q*: what are the units of \kappa? How can we interpret it?
:end:

Let's for simplicity assume that a star is all made of hydrogen (a
result first derived ~100 years ago by Cecilia Payne in her PhD thesis
in 1925). Let's also assume that it is fully ionized (i.e., protons
and electrons are separated from each other). The very minimum opacity
in this case is given by scattering of photons onto the electrons and
is: \kappa = 0.2(1+X) cm^{2} g^{-1}, where X is the mass fraction hydrogen, so
for our rough approximation, \kappa\simeq0.4. The average density of the Sun
(which you calculated for the last homework) is \rho_{\odot, avg}\simeq1.4 g
cm^{-3}, therefore \lambda_{\gamma} \simeq 2 cm. The mean-free-path for
particle-particle interactions is much smaller (because the cross
section \sigma is larger), so we can conservatively ask what is the
temperature variation across this distance:

\Delta T \simeq \lambda_{\gamma} dT/dr \le \lambda_{\gamma} T_{center}/R

(where we neglect T_{surface} because we expect it much lower than
T_{center}, since we already know P_{center} \gg P_{surface}). For the Sun we
will see that we can estimate T_{center}\simeq 10^{9} K, and we know R_{\odot},
so \Delta T\simeq 10^{-4} K \ll T_{surf} \ll T_{center}.

Thus, we can define layers of the star with \lambda_{gamma} \ll dr \ll R where
locally the temperature variation across the layer is negligible, and
the assumption of /local thermal equilibrium/ (LTE) holds well. (*N.B.:* you can
revise this a posteriori once we have an EOS!)

This may not be true close to the surface, where \lambda_{\gamma} progressively
increases (because \rho decreases). There we may need to care about the
wavelength or frequency dependance of the cross section \sigma\equiv\sigma(\nu) and
thus the mean free path: a star has a different "surface" for
different photon frequencies! In those layers, the assumption of LTE
does not work.

As long as we discuss regions of the star with a thickness large
w.r.t. \lambda_{\gamma} but small enough that the T variation across them, we
can use thermodynamics!

Also, as we have seen before, the stars are usually in equilibrium and
change very slowly. Any /local/ thermal imbalance will be restored on
the /local/ thermal timescale, which can be estimate in multiple ways,
but it is usually very short compared to the star evolutionary
timescale (we will see this in more detail later). Thus the assumption
of LTE holds locally (as the "L" indicates) at any time! Therefore,
while we cannot really define a physically meaningful T for the entire
star (beyond some rough averaged quantity), we can meaningfully define
a /local/ T(r) or T(m) temperature that characterizes the gas /and/ the
radiation at that radius/mass coordinate.

** Polytropic EOS
Polytropic EOS as a special case of /barotropic/ EOS, which are all the
EOSs for which /the density depends only on the pressure and not on
the temperature or composition/: \rho\equiv\rho(P). These have applications
beyond stellar physics (e.g., for atmospheric physics). A polytropic
EOS is thus a barotropic EOS where the \rho\equiv\rho(P) is in the form of a
powerlaw, although usually written (following the general form of Eq.
\ref{eq:general_EOS}:

#+begin_latex
\begin{equation}\label{eq:polytrope}
P = K\rho^{\Gamma} \equiv K\rho^{1+1/n}\ \ ,
\end{equation}
#+end_latex

where K is a constant, and by definition \Gamma=\partial ln P /\partial ln \rho = 1+1/n. The
form of the EOS in Eq. \ref{eq:polytrope} may seem particularly
artificial, but it is helpful because it does not introduce any new
variable, and thus "closes" (together with Eq. \ref{eq:mass_cont} and
Eq. \ref{eq:HSE}) the system of equations describing a star! This is
the system of equations used to create, for example, analytic stellar
models (e.g., the Lane-Emden equation), which is one of the topics for
the projects. These can be useful to initialize roughly correct
stellar structures in multi-D hydrodynamic codes (where we cannot/do
not want to rely on the spherical symmetry anyways).

But more importantly, there are various /physical/ situations (as we will return on
during [[./notes-lecture-EOS2.org][the second lecture on EOSs]]) in which EOS of this form occur,
and are useful to describe real observed stars.

- fully convective stars (see [[./notes-lecture-conv.org][relative lecture]])
- stars supported by quantum mechanical effects such as white dwarfs
  (WDs)

Often, different polytropes in the form of Eq. \ref{eq:polytrope} can
be used for different layers of the stars (piece-wise polytropes) as
useful approximation. In this cases, it is important to ensure the
/continuity/ of P at the points where different polytropes are stitched
together.

:Question:
- *Q*: why?
:end:

** Ideal gas
In general, it is not possible to have an EOS independent of T and/or
the composition {X_{i}}. Let's consider a /perfect gas/, that is a gas of
particles that do interact (otherwise they could never exchange energy
and be in thermal equilibrium!), but such as that the energy exchanged
in the particle-particle interactions is much small than their kinetic
energy (due to their thermal motion).

To obtain the pressure of such gas, we may need to consider the
distribution in velocity space of these particles. Let's for a moment
consider particles that all have the same mass m, we can then
equivalently consider the distribution in momentum p=mv of the
particles -- this is convenient to generalize later to relativistic
particles, and we will see how to deal with mixtures of gases (each
with particles m_{i}) further down.

Since the particles of the ideal gas move isotropically within their
volume, the momentum distribution of particles is a Maxwellian. The
number of particles with momentum between p and p+dp is

#+begin_latex
\begin{equation}\label{eq:Maxwellian}
n(p)dp = \frac{n}{(2\pi m k_{B} T)^{3/2}} \exp\left(-\frac{p^{2}}{2mk_{B}T}\right)4\pi p^{2}dp \ \ ,
\end{equation}
#+end_latex

where on the r.h.s., n is the total
density, the prefactor of the
exponential is the normalization
constant, and the exponential comes
from assuming a Gaussian
distribution of kinetic energies for
each momentum component (you can
demonstrate that a Maxwellian
distribution is equivalent to a
Gaussian in each direction p_{x}, p_{y},
p_{z}, by going to spherical-polar
coordinates in momentum space and
integrating over the p_{\theta},
p_{\varphi} components).

From this, we can calculate the
pressure of this gas. By definition
this will be isotropic, and so we
can imagine to put a "box" with unit
linear size through our gas (the
orientation of the walls does not
matter). To determine the gas
pressure we want the force exerted
by the gas on the walls. By Newton's
third law this is equal to the
change in momentum of each gas
particles as they hit the walls. We
will first consider the momentum
change for a generic single
particle, and then integrate over
the distribution in Eq.
\ref{eq:Maxwellian} to get the whole
pressure.

Let's call the imaginary wall the xy plane and assume the collisions
to be elastic (because we are considering an ideal gas, by definition
any exchange of energy is negligible). For a generic particle of the
gas, it will collide with the wall at an angle \theta \in [0, \pi/2] and the
collision will change its momentum from (p_{x}, p_{y}, p_{z}) to (p_{x}, p_{y}, -p_{z}):
only the component perpendicular to the wall changes sign. Thus

#+begin_latex
\begin{equation}
\Delta p = 2 p \cos(\theta) \mathrm{with} p=\sqrt{p_{x}^{2} + p_{y}^{2} +p_{z}^{2}}
\end{equation}
#+end_latex

The time between two collisions of a
particle on the same wall is

#+begin_latex
\begin{equation}
\Delta t = \frac{2L}{v\cos(\theta)} = \frac{2}{v\cos(\theta)} \ \ ,
\end{equation}
#+end_latex

where we used the L=1 assumption.
Thus the force exerted on this
imaginary wall of a unit box is F=\Delta
p/\Delta t = vp cos^{2}(\theta), dividing by
L^{2} = 1 we obtain the contribution to
the pressure from one particle
coming from one specific direction \theta
(w.r.t. the wall of the box), and
introducing the distribution of
particles in angle and momentum we have


#+begin_latex
\begin{equation}
dP =
vp\cos^{2}(\theta)n(\theta,p)d\theta dp \ \ ,
\end{equation}
#+end_latex

But we can assume that the motion of
the particles is isotropic, so
n(\theta,p)d\theta = n(p)sin(\theta)d\theta, and thus


#+begin_latex
\begin{equation}
dP = vp\cos^{2}(\theta)n(p)\sin(\theta)d\theta dp = \frac{1}{3}\int_{0}^{+\infty} n(p)p v dp \ \ ,
\end{equation}
#+end_latex
which combined with Eq.
\ref{eq:Maxwellian} gives the
pressure.

*** Non-relativistic, classical gas
Let's consider a non-relativistic
gas of classical particles (no
quantum effects). Then p= mv \leftrightarrow
v=p^{2}/2m (*N.B.:* we are considering an
ideal gas, so each particle is
freely moving, no potential of
interaction!)

*** The mean molecular weight
