#+title: 400A - EOS (QM effects)
#+author: Mathieu Renzo
#+email: mrenzo@arizona.edu

* Equation of state 2/2: Quantum-mechanical effects
*Materials*: Chapter 3 of Onno Pols' lecture notes, Chapter 15 and 16 of
Kippenhahn's book.

In the [[./notes-lecture-EOS1.org][previous lecture on EOS]], we have discussed polytropic EOS and
classical, non-relativistic, ideal gas. The latter is an accurate
description of the stellar gas in most, but importantly not /all/ the
astrophysical cases.

We will consider now cases that don't verify the hypothesis we took
previously and discuss briefly some stars for which we need to go
beyond those.

A star is "big", why do we need to care about quantum mechanics (QM)?
Besides its central role in allowing for nuclear burning, [[file:materials/nuclear_reaction_rates.pdf][which we
will see later]], QM effects can matter also at extremely low
temperatures and/or high densities, which can be encountered in
stellar physics.

From the wave-nature of the solutions of Schroedinger's equation, we
know that there is a limit on the precision to which position and
velocity of a particle can be known ("Heisenberg's uncertainty
principle"): \Delta x \Delta p \ge h with h Planck's constant. This naturally
translates in three spatial dimension to

#+begin_latex
\begin{equation}
\Delta x \Delta y \Delta z \Delta p_{x} \Delta p_{y} \Delta p_{z} \ge h^{3} \ \,
\end{equation}
#+end_latex

where h^{3} is the volume of a quantized cell in phase-space! Thus the
available number of quantized states with momentum between p+dp within
a volume dV is

#+begin_latex
\begin{equation}
g(p)dpdV = g_{s} \frac{4\pi p^{2} dp dV}{h^{3}} \ \mathrm{with}\ p=\sqrt{p_{x}^{2} +p_{y}^{2} +p_{z}^{2}} .
\end{equation}
#+end_latex
In the equation above, the factor g_{s} allows to account for "internal
degrees of freedom" of particles, e.g., their spin, polarization, or
isospin. The key point here is f(p)\propto p^{2} to satisfy QM.


Let's start by considering a non-extreme situation. Then the particles
are distributed according to a Maxwellian distribution n(p), but
whenever n(p)> g(p), we know this is going to violate QM!

From the [[file:notes-lecture-EOS1.org::*Ideal gas][previous lecture on EOS]] we know that the Maxwell-Boltzmann
distribution is

#+begin_latex
\begin{equation}
n(p)\propto \frac{n}{(mT)^{3/2}} \exp\left(\frac{-p^{2}}{2mk_{B} T}\right)p^{2 }\ \ ,
\end{equation}
#+end_latex

where n is the number density, T the temperature, and m the mass of
the particles. Therefore:

#+begin_latex
\begin{equation}
\frac{n(p)}{g(p)}\propto n (mT)^{-3/2}\exp(\frac{-p^{2}}{2mk_{B}T}) \ \ .
\end{equation}
#+end_latex

We can see that:

- at fixed temperature T, for very high number densities n, this ratio
  is going to be larger than one in violation of QM
- at fixed number density n, for very low temperatures, this ratio
  will be larger than 1 in violation of QM (because every term in the
  Taylor expansion of the exponential is proportional to a negative
  power of T).
- the smaller mass particle will violate QM earlier than the higher
  mass particles

Thus, we can expect that for very "cold" stars (we will define what is
the relevant scale here) or very dense stars the ideal gas EOS will not
be appropriate.

To account for QM effects, we need to consider the nature of the
particles making up the star, which can be either

- *Fermions* with semi-integer spin, such as electrons, protons,
  neutrons (and protons and neutrons can be seen as two isospin state
  of a generic nucleon, this is useful for example to discuss the
  interior composition of neutron stars). In this case, the
  distribution function that determines the occupation of quantum
  states of energy between \varepsilon\equiv\varepsilon(p) and \varepsilon+d\varepsilon is the Fermi-Dirac
  distribution:

  #+begin_latex
  \begin{equation}\label{eq:Fermi-Dirac}
   f_{FD}(\varepsilon) = \frac{1}{e^{(\varepsilon/k_{B}T - \eta)}+1} \le 1 \ \,
  \end{equation}
  #+end_latex

  where \eta=\mu/k_{b}T is the "degeneracy parameter" dependent on the
  /chemical potential \mu/ (*N.B.:* do not confuse this with the mean
  molecular weight which has the same symbol, the chemical potential
  has the dimension of an energy, while the mean molecular weight is a
  dimensionless number!) and the temperature. The fact that this is \le 1 is an
  expression of Pauli's exclusion principle, no two fermions can
  occupy the same quantum energy level.

- *Bosons* with integer spin, such as photons, or \alpha particles. In this
  case the relevant distribution is the Bose-Einstein's distribution:

  #+begin_latex
  \begin{equation}\label{eq:Bose-Einstein}
   f_{BE}(\varepsilon) = \frac{1}{e^{(\varepsilon/k_{B}T-\eta)}-1} \ \,
  \end{equation}
  #+end_latex

  which can be \ge 1, meaning more than one boson can occupy the same
  energy level (e.g., in the extreme case of a Bose-Einstein
  condensate all particles occupy the level with lowest \varepsilon).

  The total number of particles with momentum between p and p+dp is
  thus given by f(\varepsilon(p))g(p)dp for an appropriate choice of f depending
  on the particle considered (f=f_{FD} or f=f_{BE}). To determine the
  chemical potential \mu one can impose the normalization following
  from the total number density of particles:

  #+begin_latex
  \begin{equation}
  n = \int_{0}^{+\infty} f(\varepsilon(p))g(p)dp \ \ .
  \end{equation}
  #+end_latex

  Let's now consider a gas of electrons. These are the particles in
  the ionized gas of the star that will first start feeling QM
  effects, since m_{e} \ll m_{ion} (in fact m_{e} \simeq m_{proton}/2000),
  therefore, for a given temperature and density, they have much
  higher momentum p.

  In practice, the pressure provided by the /ions/ never becomes
  affected by QM directly: because of the m^{-3/2} term in the
  Maxwell-Boltzmann distribution, this would require densities so high
  that the ions would not exist as ions anymore. Instead the high
  density would allow for electron captures onto the protons of the
  ions turning them in neutrons (e^{-} + p \rightarrow n + \nu_{e}). As we will see this
  is what happens at the very end of the evolution of massive stars
  that end their life exploding and leaving a neutron-star: those
  electron capture reactions are where the neutrons come from! The
  pressure provided by the neutrons does depend on QM effects and it
  is what sustains the structure of the neutron stars!

  Because the pressure term from electrons (which in the ideal gas EOS
  is accounted for thanks to our definition of the mean molecular
  weight) changes because of QM effects first, let's now consider a
  gas made of electrons only. These particles have spin 1/2, thus they
  are fermions, and obey Eq. \ref{eq:Fermi-Dirac} and q_{s} = 2 in it
  (each quantum cell of the phase space 4\pi p^{2}dp dV can be occupied by
  2 electrons, one with spin up and one with spin down).

** Fully degenerate electron gas

  By definition, a fully degenerate gas is one where all the particles
  are in the lowest possible energy state, corresponding to the limit
  T\rightarrow0. For fermions (like the electrons we are focusing on), this
  means that the electrons occupy a sphere in momentum space with a
  radius p_{F} called the "Fermi" momentum:

  #+begin_latex
  \begin{equation}
  g_{e}(p)dp = q_{s}\frac{4\pi p^{2}}{h^{3}}dp \equiv \frac{8\pi p^{2}}{h^{3}}dp \ \  \mathrm{for} \ \
p\leq p_{F}  \ \  \mathrm{otherwise} \ \ 0 \ \ .
  \end{equation}
  #+end_latex
  Where we use q_{s}=2 for electrons. To find the value of p_{f} we can use
  the normalization coming from the total number density of electrons

  #+begin_latex
  \begin{equation}
  n_{e} = \int_{0}^{+\infty} g_{e}(p)dp = \frac{8\pi}{3h^{3}}p_{f}^{3} \Rightarrow p_{F} = h\left(\frac{3}{8\pi}n_{e}\right)^{1/3} \ \ .
  \end{equation}
  #+end_latex
  Therefore, the /Fermi momentum depends only on the density of
  electrons for a fully degenerate electron gas/.

  We can now calculate the pressure exactly like we did for the
  classical ideal gas (cf. Eq. 10 in [[file:notes-lecture-EOS1.org::*Ideal gas][the Ideal gas section]]), we just
  need the appropriate p\equiv p(\varepsilon) relaton


*** Non-relativistic electron gas

  In this case \varepsilon = p^{2}/2m is the energy of the electrons (still ideal
  gas) and v=p/m, thus from the previous lecture on EOS we have:
  #+begin_latex
  \begin{equation}
  P_{e} = \frac{1}{3}\int_{0}^{p_{F}} \frac{8\pi}{h^{3}}p^{2}\frac{p/m_{e}} p  dp = \frac{8\pi}{15 h^{3} m_{e}}p_{f}^{5} \equiv \frac{h^2}{20m_{e}}\left(\frac{3}{\pi}\right)^{2/3} n_{e}^{5/3} \ \ .
  \end{equation}
  #+end_latex

 Note the functional form P_{e}\equiv P_{e}(n_{e})! It's a powerlaw, like we
 arbitrarily assumed would be a decent guess when discussing
 polytropes. /A fully degenerate classical electron gas has a
 polytropic EOS with exponent \Gamma=5/3/.

 (to see this more explicitly you can use the definition of the
 electron mean molecular weight to substitute n_{e} for the mass density \rho).

*** Ultra-relativistic electron gas
  As the number density of electrons increases, p_{F} increases, and thus
  at some point the v=p/m we used above will not hold anymore, because
  the electrons become relativistic. In the extremely relativistic
  limit, we can assume v=c (i.e. neglect the rest energy of the
  electrons in the p(\varepsilon) relation), and then we lose one power of p in
  the integral above. Thus, in the /fully degenerate ultrarelativistic
  gas, the EOS will again be a polytrope with exponent now \Gamma=4/3/.

  Specifically the calculation yields:
  #+begin_latex
  \begin{equation}
  P_{e} = \frac{1}{3}\int_{0}^{p_{F}} \frac{8\pi}{h^{3}}p^{2}c p  dp = \frac{hc}{8}\left(\frac{3}{\pi}\right)^{1/3} n_{e}^{4/3} \ \ .
  \end{equation}
  #+end_latex

  In general, we should expect a *smooth* transition between these two
  polytopes as n_{e} increases. Since the density in a star increases
  towards the center, we can expect this transition to occur as we
  move inwards in a star where these effects matter. In this case, we
  need to use the relativistic formula p^{2} = \varepsilon^{2}-m_{e}c^{2} to solve the
  integral and obtain the pressure.

  One can estimate the electron density at the transition with the
  condition p_{F} \simeq m_{e} c.

** Partial degeneracy

  The equations derived above are valid in the strict limit of T=0,
  necessary for *full* degeneracy. Clearly, if T=0 then there is no
  thermal energy (which is the point of full degeneracy), but also a
  star would not radiate away any photon, becoming invisible and
  extremely dense (sometimes referred to as a "black dwarf"!). In
  reality it is sufficient to have k_{b}T \ll \varepsilon_{F} = p_{f}^{2}/2m (for
  non-relativistic electrons). This is equivalent to asking \eta\gg 1 with
  \eta electron degeneracy parameter.

  The transition between ideal gas and fully degenerate gas goes
  through partially degenerate gas, and in that case the degeneracy
  pressure is harder to calculate analytically, and one needs to
  calculate P = 1/3 \times \int n(p)pvdp using n(p) = g(p)f(\varepsilon(p))dp with the
  Fermi-Dirac distribution for f (in the case of electrons).

  For \eta \ll1 the Fermi-Dirac distribution can be Taylor expanded and one
  recovers the ideal gas equation of state.


  So, in summary, because electrons are Fermions that need to obey
  Pauli's principle at very low T (comparing their kinetic energy to
  the Fermi energy) and/or very high \rho, they can exert a much larger
  pressure than predicted by the classical ideal gas. Moreover, in
  those situation, the pressure is a polytrope, independent of
  temperature T! This means the stars do not need to heat up anymore
  in order to sustain themselves against their own gravity. This is
  the situation of a "white dwarf" (WD), which are the remnants for
  the vast majority of stars, including the Sun.

  These compact objects contract until they fully crystallize
  (releasing further latent heat), becoming "planet-sized diamond-like
  structures"! In the homework you will also see how there is a
  maximum mass for a WD - the so-called Chandrasekhar mass, after the
  Nobel-prize winning

** Radiation pressure

  In some stars, the radiation field is so strong that is has a
  non-negligible contribution to the pressure. The particles providing
  that pressure are photons, which are *bosons* with 2 possible
  polarization states, so q_{S} = 2 (in a classical electromagnetic wave
  language, this is because for a fixed propagation direction of a
  wave the electric field can still be in two directions, the two
  defining the plane orthogonal to the propagation direction).

  Moreover, the number of photons does not need to be conserved,
  radiative processes will destroy/create photons as needed to achieve
  equilibrium: there is no chemical potential to overcome, thus \eta=0.

  Finally, noting that the photons are ultra-relativistic by
  definition, we have \varepsilon = pc = h\nu, and the Bose-Einstein distribution
  in Eq. \ref{eq:Bose-Einstein} becomes the Black body distribution!
  We can then calculate the internal energy density of the photon gas
  as u_{int} = a T^{4} with a the radiation constant:

  #+begin_latex
  \begin{equation}
  a = \frac{8\pi^{5} k_{B}^4}{15h^{3}c^{3}} = 7.56\times10^{-15} \mathrm{erg} \ \mathrm{cm}^{-3} \ \mathrm{K}^{-4} \ \ ,
  \end{equation}
  #+end_latex

  which is closely related to the Stefan-Boltzmann constant \sigma: a=4\sigma/c.

  Relying again on the ultra-relativistic nature of photons, we know
  that P=u_{int}/3 and therefore the radiation pressure is:

  #+begin_latex
  \begin{equation}
  P_\mathrm{rad} =\frac{1}{3}aT^{4} \ \ .
  \end{equation}
  #+end_latex

** Partial ionization effects

* Total pressure in a generic star

#+begin_latex
\begin{equation}
P_\mathrm{tot} = P_\mathrm{gas} + P_\mathrm{rad} = \frac{\rho}{\mu m_{u}}k_{B}T +
P_{QM} + \frac{1}{3}aT^{4}  \ \ ,
\end{equation}
#+end_latex
where we have decomposed the gas pressure into a degeneracy term due
to quantum effects and a classical term.


* Homework

- Using the virial theorem, discuss which pressure term is more
  important in the total pressure as a function of the mass (and
  radius) of stars.
- Derive an upper limit for the temperature T as a function of the
  density \rho for a star supported by fully degenerate
  (non-relativistic) electrons, and plot this relation on a T(\rho)
  diagram. To explicit the relation between n_{e} and \rho, assume a
  composition made of pure carbon (X_{i} = 1 if carbon, 0 otherwise, Z_{i} =
  6, A_{i} = 12). Any T much lower than this limit can be considered T\simeq0
  for the purpose of the pressure calculation, but that still leaves a
  large range of non-zero T from the radiative point of view!
- Derive Chandrasekhar mass (cf. Clayton's problem 2-59)
