#+title: 400A - Radiative transfer
#+author: Mathieu Renzo
#+email: mrenzo@arizona.edu

* Stellar atmospheres

So far in this course we have mostly dealt with the /interior/ of stars
and derived equation to determine the stellar /structure/ and what
drives their /evolution/ (which is typically "slow", \tau_{nuc} \gg \tau_{KH} \gg
\tau_{ff}).

The picture we have derived is that gravity drives a contraction of
the (hot) stellar gas, which, because it has a finite temperature,
shines. This loss of internal energy translates into a loss of
gravitational potential because of the virial theorem relating the
two, and consequently the temperature in the center increases. This
continues until nuclear burning ignites to compensate for the energy
losses: /stars don't shine because they burn, stars burn _because_ they
shine/.

The nuclear burning can be seen just as an attempt by the star to
/delay/ its gravitational collapse: as nuclear fuel is depleted the star
is forced to evolve (until either gravity "wins" or the EOS deviates
from the classical ideal gas, and quantum mechanical effects provide
sufficient pressure that win over gravity, we will see these in more
detail in the coming lectures).

However, many of the assumptions we have made to derive these
equations and the picture of stellar evolution described above /do not
apply to the stellar atmosphere/, which is the layer that produces the
/detectable/ photons from stars! In this lecture we will consider in
more details the physics of the stellar atmosphere which are crucial
to obtain empirical evidence to test the picture of stellar evolution
we now can build, and to provide the outer boundary conditions needed
to calculate a stellar model.

** Definition

The /stellar atmosphere/ is by definition the layer where the radiation
field is /not/ isotropic, but the photon flux has a net /radial/
component.

*N.B.:* This does /not/ mean that all the photons move radially! Just that
on average there are more photons moving in the positive radial
direction than the negative radial direction, but photons can still
move in all direction!

This means that /by definition/ the stellar atmosphere is /not/ a black
body, and it is /partially/ transparent to photons (resulting in a
positive radial component of the photon flux). We /cannot/ use the
diffusion approximation to treat radiative transport here, since the
mean free path of photons \ell_{\gamma} are becoming comparable to the
thickness of the atmosphere (\rho decreases moving outward!).

To make models of stellar /spectra/ and determine the outer boundary
conditions we need to consider how radiation from the bottom flows
through the atmospheric layer and consequently how this layer
stratifies, determining the outer boundary pressure and temperature.

*N.B.:* real stars are even more complicated: in the photosphere
radiative and (magneto)-hydrodynamical processes can launch stellar
winds that remove mass from the star and connect smoothly the stellar
material with the interstellar material!

By definition, the bottom layer of the atmosphere is the /photosphere/,
that is this fictional surface that has T_{eff} such that a black body of
this temperature would emits the same energy per unit time as the star
does. This is /by definition/ from where the bulk of the stellar
radiation comes from (recall the [[file:notes-lecture-CMD-HRD.org::*Digression: Spectral types and the letters OBAFGKM(LTY)][discussion on spectral types!]]).

*N.B.:* dL/dm = \varepsilon_{nuc} - \varepsilon_{\nu} + \varepsilon_{grav} \equiv 0 in the outer
layers of the star where T is not high enough for nuclear burning, \rho
is not high enough for \nu emission, and we assume gravothermal
equilibrium, so \varepsilon_{grav} \propto ds/dt = 0, so L is constant.


* Basics of radiative transfer

The problem we need to consider in the stellar atmosphere is how
radiation coming from the /photosphere/ flows through the overlaying
gas, and how this impact the observable radiation itself, and the
structure of this gas.

*N.B.:* a useful thing for this problem is to "think like a photon", and
imagine the physics it will encounter through it's trip towards the
detector!

Since by definition the photosphere the radiation coming out from it
is the one of a black body, it is isotropic, so if you think of the
atmosphere as a slab of gas with a thickness dr, the radiation
illuminating it from below may come at an angle \theta w.r.t. the slab.

We can define the specific intensity (per unit frequency or
wavelength) I_{\nu} as the amount of energy flowing through a surface
element dA in a time interval dt and coming within a solid angle d\Omega
around the direction $\mathbb{n}$ with frequency in the range between
\nu and \nu+d\nu:

#+begin_latex
\begin{equation}
I_{\nu} \equiv I_{\nu}(\theta) = \frac{dI}{d\nu} = \frac{E_{\nu}}{d\nu dt dA d\Omega} \mathbb{n} \ \ ,
\end{equation}
#+end_latex

which has the dimensions of [E]/([L^{2}][t][\nu][solid angle]). This would
be constant as photons propagate along a path of length ds along the
direction $\mathbb{n}$, however there can be processes that add
photons:
- scattering from another direction onto the direction of interest,
- emission processes,
and process that can remove photons:
- scattering from the direction of propagation onto another direction
- absorption processes.
Moreover, I_{\nu} itself may in general be time dependent (although this
is not the case for stellar atmosphere), so we can write down the
equation of radiative transfer as

#+begin_latex
\begin{equation}\label{eq:radTrans}
\frac{1}{c}\frac{\partial I_{\nu}}{\partial t} + \mathbb{n}\cdot\nabla I_{\nu} = -\kappa_{\nu}\rho I_{\nu} + j_{\nu}\rho \ \ ,
\end{equation}
#+end_latex

where the l.h.s. expresses the total change in specific intensity
along the direction $\mathbb{n}$ due to the intrinsic time-dependence (\partial_{t})
of I_{\nu} and the spatial dependence along the direction we are
considering ($\mathbb{n}\cdot\nabla$), and the r.h.s. expresses the loss of
radiation intensity due to scattering /and/ absorption processes, which
depends on \kappa_{\nu} (the specific opacity we have already encountered) and
is proportional to I_{\nu} itself (you can't lose photons you don't
have!), and the addition of radiation intensity from emission
processes and scattering along the line of sight which depends on the
emission coefficient j_{\nu}.

*N.B.:* dimensional analysis reveals that each side has the units of
[I_{\nu}]/[L], this equation describes how the intensity changes along
its path. The fact that photons propagate at the speed of light c make
the leftmost factor of 1/c appear. The density \rho on the l.h.s.
expresses that the more matter there is (per unit volume), the more
likely there will be absorption and emission.

The specific intensity at the bottom of the atmosphere is related to
the photospheric emission by:

#+begin_latex
\begin{equation}
F \equiv \int_{0}^{+\infty} d\nu F_{\nu} \equiv \sigma T_\mathrm{eff}^{4} =  \int_{0}^{+\infty} d\nu \int d \Omega \cos(\theta) I_{\nu} \ \ ,
\end{equation}
#+end_latex

that is the black body flux F is obtained by integrating the specific
intensity over the solid angles. Note the factor cos(\theta) that arises
because I_{\nu} is a vector and we only want the component normal to the
surface element dA.

** Simple solutions of the steady state radiative transfer equation

*** Steady state without emission

In absence of an explicit time dependence (\partial_{t} I_{\nu} =0) and emission
processes (j_{\nu}=0), this equation is easily solved calling s the
length element along the direction $\mathbb{n}$ so that $\mathbb{n}\cdot\nabla
\equiv d/ds$, and the solution becomes:

#+begin_latex
\begin{equation}
I_{\nu} = I_{\nu,0} e^{-\kappa_{\nu}\rho s} =  I_{\nu,0} e^{-\tau_{\nu}} \ \ ,
\end{equation}
#+end_latex
where we introduce the definition of specific optical depth d\tau_{\nu} =
-\kappa_{\nu}\rho ds. This variable is useful because it gives the
scale-length of the problem as depending on \kappa_{\nu}\rho =
1/\ell_{\gamma,\nu} with \ell_{\gamma,\nu} the mean free path for a photon of
frequency between \nu and \nu+d\nu. Effectively, this allows us to use \tau_{\nu}
as the independent coordinate for the propagation of photons of
frequency between \nu and \nu+d\nu.

*** Steady state with emission and absorption canceling each other

With the definition of d\tau_{\nu}, we can re-write Eq. \ref{eq:radTrans}
(still assuming no explicit time dependence, \partial_{t}I_{\nu} = 0) as:

#+begin_latex
\begin{equation}\label{eq:rad_trans_tau}
\frac{dI_{\nu}}{d\tau_{\nu}} = \frac{j_{\nu}}{\kappa_{\nu}} - I_{\nu} \equiv S_{\nu} - I_{\nu} \ \ ,
\end{equation}
#+end_latex

where in the last step we define the source function S_{\nu}_{}. In thermal
equilibrium and at high optical depth, for instance in the interior
region of a star, dI_{\nu}/d\tau_{\nu}=0 and I_{\nu} = B(\nu,T) is the black
body function for the intensity, and this equation states S_{\nu} = I_{\nu}
\equiv B(\nu, T).

This effectively is a statement that at thermal equilibrium, the
emission processes, the absorption processes, and scattering in and
out of the direction of interest all cancel each other out.

** Eddington atmosphere

The simplest stellar atmosphere model that allows to define
non-trivial outer boundary conditions is the so called "Eddington gray
atmosphere", which provides an analytic T(\tau) relation in the
atmosphere that can be smoothly attached to the stellar interior where
T \equiv T_{eff} and used to calculate the pressure needed at such boundary to
have hydrostatic equilibrium. In other words, the Eddington gray
atmosphere allows one to define the outer boundary conditions for the
stellar interior problem.

Let's start with the assumption of a /plane parallel atmosphere/, that
is we neglect the /curvature/ of the stellar atmosphere, which is
acceptable if its radius is much larger than the length scale of
interest at any point in it. This assumption reduces the problem to a
one-dimensional problem along the vertical direction, and ds =
dz/cos(\theta) for the element of length along a generic photon path ds,
and rewrite the steady state (\partial_{t} = 0) radiative transfer equation as:

#+begin_latex
\begin{equation}
\cos(\theta)\frac{d I_{\nu}}{d\tau_{\nu}} = - (S_{\nu}-I_{\nu}) \ \ .
\end{equation}
#+end_latex

*N.B.:* There is a minus sign in the definition of d\tau_{\nu}.

The second approximation of the Eddington atmosphere is that we assume
a "gray" radiative transfer, meaning the opacity is /independent of
frequency/ \kappa_{\nu}\rightarrow\kappa, thus \tau_{\nu}\rightarrow\tau. We
also neglect the frequency dependence of the source term S_{\nu}. With
these hypotheses we can now integrate this in d\nu from 0 to +\infty and
obtain:

#+begin_latex
\begin{equation}
\cos(\theta) \frac{dI}{d\tau} = -(S-I) \ \ ,
\end{equation}
#+end_latex
which can be solved analytically (multiply by e^{-\tau/cos(\theta)},
rewrite the l.h.s. as a total derivative and integrate in d\tau) getting

#+begin_latex
\begin{equation}
I(\tau,\theta) = \frac{\exp(\tau/\cos(\theta))}{\cos(\theta)} \int_{\tau}^{+\infty} S\exp(-\tau/\cos(\theta))d\tau \ \ ,
\end{equation}
#+end_latex
where the r.h.s. is integrated from a certain optical depth \tau
outwards. We can recover the \nu dependence of S as an optical depth
dependence in this integral.

We can also define the radiation energy density u, the total flux F,
and the radiation pressure as moments of the intensity I(\tau,\theta) w.r.t.
cos(\theta) (since \theta always appears in a cosine, it is usual to change
variable to cos(\theta)=\mu in radiative transfer calculations):

#+begin_latex
\begin{equation}
u = \frac{2\pi}{c} \int_{-1}^{1} I(\tau, \theta)d\cos(\theta) \ \ ,\\
F = 2\pi\int_{-1}^{1} I(\tau, \theta)\cos(\theta)d\cos(\theta) \ \ , \\
P = \frac{2\pi}{c}\int_{-1}^{1} I(\tau, \theta)\cos^{2}(\theta)d\cos(\theta) \ \ .
\end{equation}
#+end_latex

We can also define the average specific intensity as J = 0.5\int_{-1}^{+1}
Idcos(\theta), and rewrite the

*N.B.:* While Eddington atmosphere are the simplest non-trivial case, it
is still on approximations which can (and sometimes are) relaxed in
stellar evolution modeling.



* Spectral line formation

** Saha equation

Let's also assume that LTE still holds, therefore, the rate at which
atoms are ionized I matches the rate at which there are recombinations
R (principle of detailed balance). Therefore:

#+begin_latex
\begin{equation}
 n_{e} n_{+} R = n_{0} I \Rightarrow \frac{n_{e} n_{+}}{n_{0}} = \frac{I}{R}\ \ ,
\end{equation}
#+end_latex
where n_{e}, n_{+}, and n_{0} are the number densities of electrons, positive
ions, and neutral atoms respectively (so we are imposing a balance per
unit volume). But that must also be equal to the ratio of available
states to all these particles, which in the limit of ideal gas we can
calculate using Maxwell-Boltzmann statistics! The momentum terms of
the ions and neutral atoms cancel each other in the ratio (neglecting
the small mass difference between these 2), and we are left with

#+begin_latex
\begin{equation}
\frac{n_{e} n_{+}}{n_{0}} = 2\frac{(2\pi m_{e} k_{B}T)^{3/2}}{h^{3}} \exp\left(-\frac{\chi}{k_{B}T}\right) \ \ ,
\end{equation}
#+end_latex
where the first term comes from the momentum phase space of the
electron (with 2 factor for its spin) and the exponential depends on
the ionization potential \chi.





To make things tractable, let's consider a star made of pure Hydrogen
for simplicity, since in that case we only have three possible
particles:
- neutral H (HI)
- ionized H (HII), that is a proton
- electron

:Question:
- *Q*: can there be a star of pure H astrophysically?
:end:


** Broadening mechanisms

*** Rotational broadening

*** Pressure broadening
(e.g., magnetic splitting unresolved)
