#+title: 400A - EOS (degenerate)
#+author: Mathieu Renzo
#+email: mrenzo@arizona.edu

* Equation of state 2/2
*Materials*: Chapter 3 of Onno Pols' lecture notes, Chapter 15 and 16 of
Kippenhahn's book.

In the [[./notes-lecture-EOS1.org][previous lecture on EOS]] we have dealt with a classical,
non-relativistic, ideal gas. This is an accurate description of the
stellar gas in most, but not /all/ the astrophysical cases.

We will consider now cases that don't verify the hypothesis we took
previously and discuss briefly some stars for which we need to go
beyond those.

** Quantum-mechanical effects

A star is "big", why do we need to care about quantum mechanics (QM)?
Besides its central role in allowing for nuclear burning, [[file:materials/nuclear_reaction_rates.pdf][which we
will see later]], QM effects can matter also at extremely low
temperatures and/or high densities, which can be encountered in
stellar physics.

From the wave-nature of the solutions of Schroedinger's equation, we
know that there is a limit on the precision to which position and
velocity of a particle can be known ("Heisenberg's uncertainty
principle"): \Delta x \Delta p \ge h with h Planck's constant. This naturally
translates in three spatial dimension to

#+begin_latex
\begin{equation}
\Delta x \Delta y \Delta z \Delta p_{x} \Delta p_{y} \Delta p_{z} \ge h^{3} \ \,
\end{equation}
#+end_latex

where h^{3} is the volume of a quantized cell in phase-space! Thus the
available number of quantized states with momentum between p+dp within
a volume dV is

#+begin_latex
\begin{equation}
g(p)dpdV = g_{s} \frac{4\pi p^{2} dp dV}{h^{3}} \ \mathrm{with}\ p=\sqrt{p_{x}^{2} +p_{y}^{2} +p_{z}^{2}} .
\end{equation}
#+end_latex
In the equation above, the factor g_{s} allows to account for "internal
degrees of freedom" of particles, e.g., their spin, polarization, or
isospin. The key point here is f(p)\propto p^{2} to satisfy QM.


Let's start by considering a non-extreme situation. Then the particles
are distributed according to a Maxwellian distribution n(p), but
whenever n(p) > g(p)^{}, we know this is going to violate QM!

From the [[file:notes-lecture-EOS1.org::*Ideal gas][previous lecture on EOS]] we know that the Maxwellian
distribution is n(p)\propto n/T^{3/2} exp(-p^{2}/2mk_{B} T)p^{2}, so n(p)/g(p)\propto n T^{-3/2}^{}
exp(-p^{2}^{}/2mk_{B}T). We can see that:

- at fixed temperature T, for very high number densities n, this ratio
  is going to be larger than one in violation of QM
- at fixed number density n, for very low temperatures, this ratio
  will be larger than 1 in violation of QM (because every term in the
  Taylor expansion of the exponential is proportional to a negative
  power of T).

Thus, we can expect that for very "cold" stars (we will define what is
the relevant scale here) or vey dense stars the ideal gas EOS will not
be appropriate.

To account for QM effects, we need to consider the nature of the
particles making up the star, which can be either

- *Fermions* with semi-integer spin, such as electrons, protons,
  neutrons (and protons and neutrons can be seen as two isospin state
  of a generic nucleon, this is useful for example to discuss the
  interior composition of neutron stars). In this case, the
  distribution function that determines the occupation of quantum
  states of energy between \varepsilon and \varepsilon+d\varepsilon is the Fermi-Dirac distribution:

  #+begin_latex
  \begin{equation}
   f_{FD}(\varepsilon) = \frac{1}{e^{(\varepsilon/k_{B}T - \eta)}+1} \le 1 \ \,
  \end{equation}
  #+end_latex

  where \mu is the /chemical potential/ (*N.B.:* do not confuse this with
  the mean molecular weight which has the same symbol, the chemical
  potential has the dimension of an energy, while the mean molecular
  weight is a dimensionless number!) and \varepsilon\equiv\varepsilon(p). The fact that this is
  \le 1 is an expression of Pauli's exclusion principle, no two fermions
  can occupy the same quantum energy level.

- *Bosons* with integer spin, such as photons, or \alpha particles. In this
  case the relevant distribution is the Bose-Einstein's distribution:

  #+begin_latex
  \begin{equation}
   f_{BE}(\varepsilon) = \frac{1}{e^{(\varepsilon/k_{B}T-\eta)}-1} \ \,
  \end{equation}
  #+end_latex

  which can be \ge 1, meaning more than one boson can occupy the same
  energy level (e.g., in the extreme case of a Bose-Einstein
  condensate all particles occupy the level with lowest \varepsilon).

  The total number of particles with momentum between p and p+dp is
  thus given by f(\varepsilon(p))g(p)dp for an appropriate choice of f depending
  on the particle considered (f=f_{FD} or f=f_{BE}). To determine the
  chemical potential \mu one can impose the normalization following
  from the total number density of particles:

  #+begin_latex
  \begin{equation}
  n = \int_{0}^{+\infty} f(\varepsilon(p))g(p)dp \ \ .
  \end{equation}
  #+end_latex

  We know these
*** Non-relativistic gas

*** Relativistic gas

** Radiation pressure

** Total pressure in a generic star

#+begin_latex
\begin{equation}
P_\mathrm{tot} = P_\mathrm{gas} + P_\mathrm{rad} = \frac{\rho}{\mu m_{u}}k_{B}T +
P_{QM} + \frac{1}{3}aT^{4}  \ \ ,
\end{equation}
#+end_latex
where we have decomposed the gas pressure into a degeneracy term due
to quantum effects and a classical term.


* Homework

Derive Chandrasekhar mass?

- Using the virial theorem, discuss which pressure term is more
  important in the total pressure as a function of the mass (and
  radius) of stars.
