#+title: 400A Syllabus - Stellar Evolution
#+author: Mathieu Renzo
#+email: mrenzo@arizona.edu
#+PREVIOUS_PAGE: index.org
#+NEXT_PAGE: projects.org

* Description of the course
The main topic of the course is stellar structure, a field of
astronomy that brings together many different branches of physics
(hydrodynamics, atomic, nuclear, and neutrino physics,
radiation-matter interactions, etc.) to understand the fundamental
objects of astronomical study: stars.

See also [[./lectures.org][here]] for a breakdown of the main topics covered and [[file:projects.org::*List of possible projects/presentations][here]] for
a tentative list of topics covered by student presentations.

* Where and when
Steward Observatory room *204*, Tuesday and Thursday 11:00 am-12:15 pm.

* Instructor
** Prof. Mathieu Renzo
- Office: N506
- Email: [[mailto:mrenzo@arizona.edu][mrenzo@arizona.edu]]
- Office hours: by appointment to be scheduled by email

*N.B.:* Office hours are times set aside to help you! Please come and
ask any questions you have. My availability is different every week,
so please reach out to schedule an appointment. Email is the best way
to get in touch with me, but given my schedule, I may not respond for
a full business day. Please plan ahead.

* Expected learning outcomes
By the end of the course, students will be able to:

 - *Understand the physical scales associated with a wide variety of
   astronomical objects and phenomena.*
 - *Apply a physically motivated theoretical framework to stellar
   structure to derive stellar properties and compare to observations.*
 - *Use mathematical and computational skills to solve astrophysical
   problems related to stars and more generally astrophysics.*
 - *Communicating, translating, and interpreting fundamental
   astronomical concepts and research results.*
 - *Distinguish observationally confirmed elements of stellar physics
   from numerical results.*

These learning outcomes will be met through attendance at lectures,
in-class activities, homework and writing assignments, and a final
literature review project made of written and oral presentation on a
selected topic. See [[./projects.org][Projects]] for more information, including a list of
possible topics.

* Course format and teaching methods
This course relies on frontal lectures, homework, and in-class problem
solving activities (individual and in group), and student
presentations. Some problem solving activities will be of
computational nature.

This is also a class with "writing emphasis", which will be included
as part of homework and the final presentation.

* Recommended textbooks and resources
Most stellar physics text books will contain most of the information
covered in this course, although order and presentation vary. You can
use any textbook you like or already have. I recommend and will mostly
follow these:

 - [[https://www.astro.ru.nl/~onnop/][Prof. Onno Pols notes]]. These lecture notes are freely available,
   accessible, and thorough, making them an excellent starting point.
   I strongly suggest downloading a copy for yourself early in the
   course.
 - [[https://link.springer.com/book/10.1007/978-3-642-30304-3][Kippenhahn, Weigert, & Weiss 2012]]. This is a classic textbook that
   you may continue to consult even as a seasoned researcher with
   emphasis on the physical processes in stars. If you are an enrolled
   student and have troubles accessing this book, please come talk to
   me.

We will also use [[http://user.astro.wisc.edu/~townsend/static.php?ref=mesa-web-submit][MESA-web]], a cloud-computing resource to run stellar
evolution simulations with the open-source, community-developed, code
[[https://docs.mesastar.org/en/latest/][MESA]].

* Exams and grading
The course grade will be based on:
 - In class participation: 20%
 - Homework: 40%
 - Literature review project/presentation (written+oral): 40%

The class will not be curved, and this will be the correspondence
between final percentages and letter grades:
 - A: 85-100%
 - B: 70-85%
 - C: 50-70%
 - D: 30-50%
 - E: 0-30%

** Participation
Your engagement, quality of contributions, and interactions with the
instructors and with your peers will contribute to your final grade.
Quality and frequency of your contributions will be evaluated
throughout the course, rewarding specifically *growth* and *improvement*.

*N.B.:* I will not log attendance, being there is *not a sufficient*
condition to guarantee a good participation grade.

*** Rubric for in class participation

  The rubric used to evaluate the in class participation is given below.
  I will keep track of relevant and/or insightful questions/comments in
  class and/or at office hours.

#+ATTR_LATEX: :font \tiny :float sideways
  |---------------+------------------------------------------+-------------------------------------+-----------------------------------+-----------------------------------------|
  |               | Rubric for in class participation        |                                     |                                   |                                         |
  |---------------+------------------------------------------+-------------------------------------+-----------------------------------+-----------------------------------------|
  |               | Exceptional                              | Very good                           | Adequate                          | Poor                                    |
  |---------------+------------------------------------------+-------------------------------------+-----------------------------------+-----------------------------------------|
  | Engagement    | Consistent proactive                     | Frequent active participation       | Occasional participation during   | Rare or absent participation,           |
  |               | participation during lectures and        | during lectures and other in class  | lectures and in class activities  | or frequent but disruptive              |
  |               | other in class activities with valuable  | activities with valuable            | with relevant contribution        | interruptions with rarely relevant      |
  |               | insights and/or pertinent questions      | insight and question                |                                   | and often beside-the-point              |
  |               |                                          |                                     |                                   | interventions                           |
  |---------------+------------------------------------------+-------------------------------------+-----------------------------------+-----------------------------------------|
  | Preparation   | Consistent demonstration                 | Consistent demonstration of         | Typically good understanding      | Lack of understanding of the            |
  |               | of thorough and in depth                 | thorough understanding of           | of material covered in            | materials already covered in            |
  |               | understanding of course content          | course content already covered      | the course with only              | class and past homework.                |
  |               | covered /and knowledge of/                 |                                     | occasional misunderstandings of   | Severe misconceptions unaddressed.      |
  |               | topical content beyond the course        |                                     | previously covered content        |                                         |
  |               |                                          |                                     |                                   |                                         |
  |---------------+------------------------------------------+-------------------------------------+-----------------------------------+-----------------------------------------|
  | Collaboration | Consistent level of engagement           | Consistent level of engagement      | Typically proactive participation | Disengaged from group activities,       |
  |               | with peers, exhibiting "leadership"      | with peers, with positive           | in group activities with positive | lets others do all the work.            |
  |               | and "peer mentoring" qualities,          | contributions to group activities   | contribution                      | Does not let others contribute          |
  |               | enabling and helping the participation   | and occasionally helping others     |                                   | and learn together, participation       |
  |               | and development of others and themselves |                                     |                                   | is a net negative in content and        |
  |               |                                          |                                     |                                   | climate within the group                |
  |---------------+------------------------------------------+-------------------------------------+-----------------------------------+-----------------------------------------|
  | Growth        | Shows significant improvement            | Demonstrates noticeable improvement | Demonstrates some improvement     | Demonstrates marginal or no improvement |
  |               | in engagement, preparation, and          | in engagement, preparation, and     | in engagement, preparation, and   | in engagement, preparation, and         |
  |               | collaboration over the semester          | collaboration over the semester     | collaboration over the semester   | collaboration over the semester         |
  |---------------+------------------------------------------+-------------------------------------+-----------------------------------+-----------------------------------------|


  Roughly between one-third and halfway through the course, depending
  on how lectures proceed, you will receive feedback on
  your participation in class.

** Homework

There will be regular homework assignments, including
order-of-magnitude, quantitative, computational and/or more
qualitative exercises, depending on the week and topic. Please feel
free to use resources outside of the textbook. You can also
collaborate with your peers, but please *each time you do, indicate
with whom*. You *must* show your individual work to receive full credit.

Assignments should be uploaded *in pdf form* via D2L. Deadlines will be
designed to use the homework materials in class. *Late submissions will
not be accepted unless explicitly agreed upon beforehand*, if you
expect not to make it on time, ask for an extension *at least one day
before the deadline*. It's better to submit something incomplete than
nothing. In your pdf files, you should show the calculations done and
contextualise them as appropriate.

Timely feedback will be provided for you to assess your understanding
and progress.

** Literature review project and presentation
You will be assigned a topic relevant to the course to explain to your
peers. You will search the literature and prepare a written text plus
an oral presentation. The written text will be evaluated both by the
instructor and two randomly selected peers, the oral presentation will
be evaluated by all the student present plus the instructors. For more
information on the literature review project/presentation and how it
will be graded, see [[./projects.org][here]].

** Incomplete (I) or Withdrawal (W):
Requests for incomplete (I) or withdrawal (W) must be made in
accordance with University policies, which are available at
https://registrar.arizona.edu/faculty-staff-resources/grading/grading-policies/incomplete
and
https://registrar.arizona.edu/faculty-staff-resources/grading/grading-policies/withdrawals,
respectively.

* Classroom Behavior
To foster a positive learning environment, students and instructors
have a shared responsibility. We want a safe, welcoming, and inclusive
environment where all of us feel comfortable with each other and where
we can challenge ourselves to succeed. To that end, our focus is on
the tasks at hand and not on extraneous activities (e.g., texting,
chatting, web surfing, etc.). Students are asked to refrain from
disruptive conversations with people sitting around them during
lecture. Students observed engaging in disruptive activity will be
asked to cease this behavior. Those who continue to disrupt the class
will be asked to leave lecture or discussion and may be reported to
the Dean of Students.

The Arizona Board of Regents’ Student Code of Conduct, ABOR Policy
5‐308, prohibits threats of physical harm to any member of the
University community, including to one’s self. See:
[[http://policy.web.arizona.edu/threatening‐behavior‐students]]

Any social media groups generated using university-sponsored tools
(e.g., D2L class lists, slack workspaces) should be treated as an
extension of the classroom. This means that they will need to abide by
the University’s student code of conduct policies, and be respectful,
inclusive environments.

** Nondiscrimination and Anti-harassment Policy
The University of Arizona is committed to creating and maintaining an
environment free of discrimination. In support of this commitment, the
University prohibits discrimination, including harassment and
retaliation, based on a protected classification, including race,
color, religion, sex, national origin, age, disability, veteran
status, sexual orientation, gender identity, or genetic information.
For more information, including how to report a concern, please see
http://policy.arizona.edu/human-resources/nondiscrimination-and-anti-harassment-policy

** Accessibility and accommodations
At the University of Arizona, we strive to make learning
experiences as accessible as possible. If you anticipate or
experience barriers based on disability or pregnancy, please
contact the Disability Resource Center (520-621-3268,
https://drc.arizona.edu/) to establish reasonable accommodations.

** Class recordings
To facilitate everyone's participation, audio and/or video recording
of in class activities is not allowed unless explicitly agreed upon by
all present students /and/ instructors. In no case sharing on public
platforms of the recordings will be allowed.

** Preferred Name and Pronoun
This course affirms people of all gender expressions and gender
identities. If you prefer to be called a different name than what is
on the class roster, please let me know. Feel free to correct
instructors on your preferred gender pronoun.

* Attendance Policy
All holidays or special events observed by organized religions will be
honored for those students who show affiliation with that particular
religion. Absences pre‐approved by the UA Dean of Students (or Dean's
designee) will be honored.

It is important to attend all classes, as what is discussed in class
is pertinent to adequate performance on assignments and exams. If you
must be absent, it is your responsibility to obtain and review the
information you missed.

* Academic Integrity
Integrity is expected of every student in all academic work. The
guiding principle of academic integrity is that a student’s submitted
work must be the student’s own. Students are encouraged to share
intellectual views and discuss freely the principles and applications
of course materials. However, *graded work/exercises must be the
product of your own effort unless otherwise instructed*. Students are
expected to adhere to the UA Code of Academic Integrity as described
in the UA General Catalog. See:
[[https://deanofstudents.arizona.edu/student-rights-responsibilities/academic-integrity]]

Misappropriation of exams before or after they are given will be
considered academic misconduct. Misconduct of any kind will be
prosecuted and may result in any or all of the following:
- Reduction of grade
- Failing grade
- Referral to the Dean of Students for consideration of additional
  penalty, i.e. notation on a student’s transcript re. academic
  integrity violation, etc. [[http://deanofstudents.arizona.edu/policies‐and‐codes/code‐academic‐integrity]]

* Additional resources for students
UA Academic policies and procedures are available at
http://catalog.arizona.edu/policies

** Campus Health
http://www.health.arizona.edu/

Campus Health provides quality medical and mental health care services
through virtual and in-person care.

- Phone: 520-621-9202

** Counseling and Psych Services (CAPS)
https://health.arizona.edu/counseling-psych-services

CAPS provides mental health care, including short-term counseling
services.

- Phone: 520-621-3334

** The Dean of Students Office’s Student Assistance Program
http://deanofstudents.arizona.edu/student-assistance/students/student-assistance

Student Assistance helps students manage crises, life traumas, and
other barriers that impede success. The staff addresses the needs of
students who experience issues related to social adjustment, academic
challenges, psychological health, physical health, victimization, and
relationship issues, through a variety of interventions, referrals,
and follow up services.

- Email: [[mailto:DOS-deanofstudents@email.arizona.edu][DOS-deanofstudents@email.arizona.edu]]
- Phone: 520-621-7057

** Survivor Advocacy Program
https://survivoradvocacy.arizona.edu/

The Survivor Advocacy Program provides confidential support and
advocacy services to student survivors of sexual and gender-based
violence. The Program can also advise students about relevant non-UA
resources available within the local community for support.

- Email: [[mailto:survivoradvocacy@email.arizona.edu][survivoradvocacy@email.arizona.edu]]
- Phone: 520-621-5767

** Support Outreach Success (SOS)
https://sos.arizona.edu/about

Students who ask for help are more successful. If you have questions,
concerns or challenges and are unsure about where to go for answers or
support you can ask SOS. The SOS staff will answer questions, find you
resources or connect you with the correct people. Whether you’re
brand-new to campus or have been around for a while, just reach out to
SOS for support.

- Chat: [[http://sos.arizona.edu][sos.arizona.edu]]
- Email: [[mailto:sos@arizona.edu][sos@arizona.edu]]
- Text: SOS to 70542
- Call: 520-621-2327

* Confidentiality of Student Records
http://www.registrar.arizona.edu/ferpa

* Safety on Campus and in the Classroom
For a list of emergency procedures for all types of incidents, please visit the website of the Critical
Incident Response Team (CIRT): https://cirt.arizona.edu/case-emergency/overview

Also watch the video available at
https://arizona.sabacloud.com/Saba/Web_spf/NA7P1PRD161/common/learningeventdetail/crtfy000000000003560

* Subject to change statement
The information contained in this syllabus, other than the grade and absence
policies, may be subject to change with reasonable advance notice, as deemed
appropriate by the instructor.
